/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from '../../app/app.module';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '@angular/core/src/application_module';
import * as import4 from '@angular/platform-browser/src/browser';
import * as import5 from '@angular/forms/src/directives';
import * as import6 from '@angular/forms/src/form_providers';
import * as import7 from '@angular/http/src/http_module';
import * as import8 from '@angular/material/core/compatibility/default-mode';
import * as import9 from '@angular/material/core/ripple/ripple';
import * as import10 from '@angular/material/core/option/option';
import * as import11 from '@angular/material/core/portal/portal-directives';
import * as import12 from '@angular/material/core/overlay/overlay-directives';
import * as import13 from '@angular/material/autocomplete/index';
import * as import14 from '@angular/material/button/button';
import * as import15 from '@angular/material/card/card';
import * as import16 from '@angular/material/chips/chip-list';
import * as import17 from '@angular/material/checkbox/checkbox';
import * as import18 from '@angular/material/core/line/line';
import * as import19 from '@angular/material/grid-list/grid-list';
import * as import20 from '@angular/material/core/platform/index';
import * as import21 from '@angular/material/input/input';
import * as import22 from '@angular/material/list/list';
import * as import23 from '@angular/material/progress-bar/progress-bar';
import * as import24 from '@angular/material/progress-spinner/progress-spinner';
import * as import25 from '@angular/material/select/index';
import * as import26 from '@angular/material/core/a11y/index';
import * as import27 from '@angular/material/sidenav/sidenav';
import * as import28 from '@angular/material/core/observe-content/observe-content';
import * as import29 from '@angular/material/tabs/tab-group';
import * as import30 from '@angular/material/toolbar/toolbar';
import * as import31 from '@angular/material/core/projection/projection';
import * as import32 from '@angular/material/core/rtl/dir';
import * as import33 from '@angular/material/button-toggle/button-toggle';
import * as import34 from '@angular/material/dialog/index';
import * as import35 from '@angular/material/icon/icon';
import * as import36 from '@angular/material/menu/menu';
import * as import37 from '@angular/material/radio/radio';
import * as import38 from '@angular/material/slider/slider';
import * as import39 from '@angular/material/slide-toggle/slide-toggle';
import * as import40 from '@angular/material/snack-bar/snack-bar';
import * as import41 from '@angular/material/tooltip/tooltip';
import * as import42 from '@angular/material/module';
import * as import43 from '@angular/router/src/router_module';
import * as import44 from '../../app/app-routing.module';
import * as import45 from '@angular/common/src/localization';
import * as import46 from '@angular/core/src/application_init';
import * as import47 from '@angular/core/src/testability/testability';
import * as import48 from '@angular/core/src/application_ref';
import * as import49 from '@angular/core/src/linker/compiler';
import * as import50 from '@angular/material/core/gestures/gesture-config';
import * as import51 from '@angular/platform-browser/src/dom/events/event_manager';
import * as import52 from '@angular/platform-browser/src/dom/shared_styles_host';
import * as import53 from '@angular/platform-browser/src/dom/dom_renderer';
import * as import54 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import55 from '@angular/core/src/animation/animation_queue';
import * as import56 from '@angular/core/src/linker/view_utils';
import * as import57 from '@angular/platform-browser/src/browser/title';
import * as import58 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import59 from '@angular/http/src/backends/browser_xhr';
import * as import60 from '@angular/http/src/base_response_options';
import * as import61 from '@angular/http/src/backends/xhr_backend';
import * as import62 from '@angular/http/src/base_request_options';
import * as import63 from '@angular/material/core/overlay/position/overlay-position-builder';
import * as import64 from '@angular/material/core/overlay/overlay';
import * as import65 from '@angular/material/core/platform/platform';
import * as import66 from '@angular/material/core/a11y/interactivity-checker';
import * as import67 from '@angular/material/dialog/dialog';
import * as import68 from '@angular/common/src/location/location';
import * as import69 from '@angular/router/src/url_tree';
import * as import70 from '@angular/router/src/router_outlet_map';
import * as import71 from '@angular/core/src/linker/system_js_ng_module_factory_loader';
import * as import72 from '@angular/router/src/router_preloader';
import * as import73 from '../../app/services/authentication.service';
import * as import74 from '../../app/app.authguard';
import * as import75 from '../../app/services/data.service';
import * as import76 from '@angular/core/src/di/injector';
import * as import77 from '../node_modules/@angular/material/dialog/dialog-container.ngfactory';
import * as import78 from '../node_modules/@angular/material/snack-bar/snack-bar-container.ngfactory';
import * as import79 from '../node_modules/@angular/material/snack-bar/simple-snack-bar.ngfactory';
import * as import80 from '../node_modules/@angular/material/tooltip/tooltip.ngfactory';
import * as import81 from './app.component.ngfactory';
import * as import82 from './components/home.component.ngfactory';
import * as import83 from './components/take-quiz.component.ngfactory';
import * as import84 from './components/dashboard.component.ngfactory';
import * as import85 from './components/quizes.component.ngfactory';
import * as import86 from '@angular/core/src/i18n/tokens';
import * as import87 from '@angular/core/src/application_tokens';
import * as import88 from '@angular/platform-browser/src/dom/events/dom_events';
import * as import89 from '@angular/platform-browser/src/dom/events/key_events';
import * as import90 from '@angular/platform-browser/src/dom/events/hammer_gestures';
import * as import91 from '@angular/core/src/zone/ng_zone';
import * as import92 from '@angular/platform-browser/src/dom/debug/ng_probe';
import * as import93 from '@angular/material/core/overlay/position/viewport-ruler';
import * as import94 from '@angular/material/core/overlay/overlay-container';
import * as import95 from '@angular/material/core/overlay/scroll/scroll-dispatcher';
import * as import96 from '@angular/material/core/a11y/live-announcer';
import * as import97 from '@angular/material/core/coordination/unique-selection-dispatcher';
import * as import98 from '@angular/material/icon/icon-registry';
import * as import99 from '@angular/common/src/location/platform_location';
import * as import100 from '@angular/common/src/location/location_strategy';
import * as import101 from '../../app/app.component';
import * as import102 from '../../app/components/home.component';
import * as import103 from '../../app/components/take-quiz.component';
import * as import104 from '../../app/components/dashboard.component';
import * as import105 from '../../app/components/quizes.component';
import * as import106 from '@angular/router/src/url_handling_strategy';
import * as import107 from '@angular/router/src/route_reuse_strategy';
import * as import108 from '@angular/router/src/router';
import * as import109 from '@angular/core/src/console';
import * as import110 from '@angular/core/src/error_handler';
import * as import111 from '@angular/platform-browser/src/dom/dom_tokens';
import * as import112 from '@angular/platform-browser/src/dom/animation_driver';
import * as import113 from '@angular/core/src/render/api';
import * as import114 from '@angular/core/src/security';
import * as import115 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import116 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import117 from '@angular/http/src/interfaces';
import * as import118 from '@angular/http/src/http';
import * as import119 from '@angular/core/src/linker/ng_module_factory_loader';
import * as import120 from '@angular/router/src/router_config_loader';
import * as import121 from '@angular/router/src/router_state';
class AppModuleInjector extends import0.NgModuleInjector<import1.AppModule> {
  _CommonModule_0:import2.CommonModule;
  _ApplicationModule_1:import3.ApplicationModule;
  _BrowserModule_2:import4.BrowserModule;
  _InternalFormsSharedModule_3:import5.InternalFormsSharedModule;
  _FormsModule_4:import6.FormsModule;
  _HttpModule_5:import7.HttpModule;
  _DefaultStyleCompatibilityModeModule_6:import8.DefaultStyleCompatibilityModeModule;
  _MdRippleModule_7:import9.MdRippleModule;
  _MdOptionModule_8:import10.MdOptionModule;
  _PortalModule_9:import11.PortalModule;
  _OverlayModule_10:import12.OverlayModule;
  _MdAutocompleteModule_11:import13.MdAutocompleteModule;
  _MdButtonModule_12:import14.MdButtonModule;
  _MdCardModule_13:import15.MdCardModule;
  _MdChipsModule_14:import16.MdChipsModule;
  _MdCheckboxModule_15:import17.MdCheckboxModule;
  _MdLineModule_16:import18.MdLineModule;
  _MdGridListModule_17:import19.MdGridListModule;
  _PlatformModule_18:import20.PlatformModule;
  _MdInputModule_19:import21.MdInputModule;
  _MdListModule_20:import22.MdListModule;
  _MdProgressBarModule_21:import23.MdProgressBarModule;
  _MdProgressSpinnerModule_22:import24.MdProgressSpinnerModule;
  _MdSelectModule_23:import25.MdSelectModule;
  _A11yModule_24:import26.A11yModule;
  _MdSidenavModule_25:import27.MdSidenavModule;
  _ObserveContentModule_26:import28.ObserveContentModule;
  _MdTabsModule_27:import29.MdTabsModule;
  _MdToolbarModule_28:import30.MdToolbarModule;
  _ProjectionModule_29:import31.ProjectionModule;
  _RtlModule_30:import32.RtlModule;
  _MdButtonToggleModule_31:import33.MdButtonToggleModule;
  _MdDialogModule_32:import34.MdDialogModule;
  _MdIconModule_33:import35.MdIconModule;
  _MdMenuModule_34:import36.MdMenuModule;
  _MdRadioModule_35:import37.MdRadioModule;
  _MdSliderModule_36:import38.MdSliderModule;
  _MdSlideToggleModule_37:import39.MdSlideToggleModule;
  _MdSnackBarModule_38:import40.MdSnackBarModule;
  _MdTooltipModule_39:import41.MdTooltipModule;
  _MaterialRootModule_40:import42.MaterialRootModule;
  _ROUTER_FORROOT_GUARD_41:any;
  _RouterModule_42:import43.RouterModule;
  _AppRoutingModule_43:import44.AppRoutingModule;
  _AppModule_44:import1.AppModule;
  __LOCALE_ID_45:any;
  __NgLocalization_46:import45.NgLocaleLocalization;
  _ErrorHandler_47:any;
  _ApplicationInitStatus_48:import46.ApplicationInitStatus;
  _Testability_49:import47.Testability;
  _ApplicationRef__50:import48.ApplicationRef_;
  __ApplicationRef_51:any;
  __Compiler_52:import49.Compiler;
  __APP_ID_53:any;
  __DOCUMENT_54:any;
  __HAMMER_GESTURE_CONFIG_55:import50.GestureConfig;
  __EVENT_MANAGER_PLUGINS_56:any[];
  __EventManager_57:import51.EventManager;
  __DomSharedStylesHost_58:import52.DomSharedStylesHost;
  __AnimationDriver_59:any;
  __DomRootRenderer_60:import53.DomRootRenderer_;
  __NgProbeToken_61:any[];
  __RootRenderer_62:any;
  __DomSanitizer_63:import54.DomSanitizerImpl;
  __Sanitizer_64:any;
  __AnimationQueue_65:import55.AnimationQueue;
  __ViewUtils_66:import56.ViewUtils;
  __IterableDiffers_67:any;
  __KeyValueDiffers_68:any;
  __SharedStylesHost_69:any;
  __Title_70:import57.Title;
  __RadioControlRegistry_71:import58.RadioControlRegistry;
  __BrowserXhr_72:import59.BrowserXhr;
  __ResponseOptions_73:import60.BaseResponseOptions;
  __XSRFStrategy_74:any;
  __XHRBackend_75:import61.XHRBackend;
  __RequestOptions_76:import62.BaseRequestOptions;
  __Http_77:any;
  __MATERIAL_COMPATIBILITY_MODE_78:any;
  __ViewportRuler_79:any;
  __OverlayContainer_80:any;
  __OverlayPositionBuilder_81:import63.OverlayPositionBuilder;
  __Overlay_82:import64.Overlay;
  __ScrollDispatcher_83:any;
  __Platform_84:import65.Platform;
  __InteractivityChecker_85:import66.InteractivityChecker;
  __LiveAnnouncer_86:any;
  __DomProjection_87:import31.DomProjection;
  __UniqueSelectionDispatcher_88:any;
  __MdDialog_89:import67.MdDialog;
  __MdIconRegistry_90:any;
  __MdSnackBar_91:import40.MdSnackBar;
  __ROUTER_CONFIGURATION_92:any;
  __LocationStrategy_93:any;
  __Location_94:import68.Location;
  __UrlSerializer_95:import69.DefaultUrlSerializer;
  __RouterOutletMap_96:import70.RouterOutletMap;
  __NgModuleFactoryLoader_97:import71.SystemJsNgModuleLoader;
  __ROUTES_98:any[];
  __Router_99:any;
  __ActivatedRoute_100:any;
  _NoPreloading_101:import72.NoPreloading;
  _PreloadingStrategy_102:any;
  _RouterPreloader_103:import72.RouterPreloader;
  __PreloadAllModules_104:import72.PreloadAllModules;
  __ROUTER_INITIALIZER_105:any;
  __APP_BOOTSTRAP_LISTENER_106:any[];
  __AuthenticationService_107:import73.AuthenticationService;
  __AuthGuard_108:import74.AuthGuard;
  __DataService_109:import75.DataService;
  constructor(parent:import76.Injector) {
    super(parent,[
      import77.MdDialogContainerNgFactory,
      import78.MdSnackBarContainerNgFactory,
      import79.SimpleSnackBarNgFactory,
      import80.TooltipComponentNgFactory,
      import81.AppComponentNgFactory,
      import82.HomeComponentNgFactory,
      import83.TakeQuizComponentNgFactory,
      import84.DashboardComponentNgFactory,
      import85.QuizesComponentNgFactory
    ]
    ,[import81.AppComponentNgFactory]);
  }
  get _LOCALE_ID_45():any {
    if ((this.__LOCALE_ID_45 == null)) { (this.__LOCALE_ID_45 = import3._localeFactory(this.parent.get(import86.LOCALE_ID,(null as any)))); }
    return this.__LOCALE_ID_45;
  }
  get _NgLocalization_46():import45.NgLocaleLocalization {
    if ((this.__NgLocalization_46 == null)) { (this.__NgLocalization_46 = new import45.NgLocaleLocalization(this._LOCALE_ID_45)); }
    return this.__NgLocalization_46;
  }
  get _ApplicationRef_51():any {
    if ((this.__ApplicationRef_51 == null)) { (this.__ApplicationRef_51 = this._ApplicationRef__50); }
    return this.__ApplicationRef_51;
  }
  get _Compiler_52():import49.Compiler {
    if ((this.__Compiler_52 == null)) { (this.__Compiler_52 = new import49.Compiler()); }
    return this.__Compiler_52;
  }
  get _APP_ID_53():any {
    if ((this.__APP_ID_53 == null)) { (this.__APP_ID_53 = import87._appIdRandomProviderFactory()); }
    return this.__APP_ID_53;
  }
  get _DOCUMENT_54():any {
    if ((this.__DOCUMENT_54 == null)) { (this.__DOCUMENT_54 = import4._document()); }
    return this.__DOCUMENT_54;
  }
  get _HAMMER_GESTURE_CONFIG_55():import50.GestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_55 == null)) { (this.__HAMMER_GESTURE_CONFIG_55 = new import50.GestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_55;
  }
  get _EVENT_MANAGER_PLUGINS_56():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_56 == null)) { (this.__EVENT_MANAGER_PLUGINS_56 = [
      new import88.DomEventsPlugin(),
      new import89.KeyEventsPlugin(),
      new import90.HammerGesturesPlugin(this._HAMMER_GESTURE_CONFIG_55)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_56;
  }
  get _EventManager_57():import51.EventManager {
    if ((this.__EventManager_57 == null)) { (this.__EventManager_57 = new import51.EventManager(this._EVENT_MANAGER_PLUGINS_56,this.parent.get(import91.NgZone))); }
    return this.__EventManager_57;
  }
  get _DomSharedStylesHost_58():import52.DomSharedStylesHost {
    if ((this.__DomSharedStylesHost_58 == null)) { (this.__DomSharedStylesHost_58 = new import52.DomSharedStylesHost(this._DOCUMENT_54)); }
    return this.__DomSharedStylesHost_58;
  }
  get _AnimationDriver_59():any {
    if ((this.__AnimationDriver_59 == null)) { (this.__AnimationDriver_59 = import4._resolveDefaultAnimationDriver()); }
    return this.__AnimationDriver_59;
  }
  get _DomRootRenderer_60():import53.DomRootRenderer_ {
    if ((this.__DomRootRenderer_60 == null)) { (this.__DomRootRenderer_60 = new import53.DomRootRenderer_(this._DOCUMENT_54,this._EventManager_57,this._DomSharedStylesHost_58,this._AnimationDriver_59,this._APP_ID_53)); }
    return this.__DomRootRenderer_60;
  }
  get _NgProbeToken_61():any[] {
    if ((this.__NgProbeToken_61 == null)) { (this.__NgProbeToken_61 = [import43.routerNgProbeToken()]); }
    return this.__NgProbeToken_61;
  }
  get _RootRenderer_62():any {
    if ((this.__RootRenderer_62 == null)) { (this.__RootRenderer_62 = import92._createConditionalRootRenderer(this._DomRootRenderer_60,this.parent.get(import92.NgProbeToken,(null as any)),this._NgProbeToken_61)); }
    return this.__RootRenderer_62;
  }
  get _DomSanitizer_63():import54.DomSanitizerImpl {
    if ((this.__DomSanitizer_63 == null)) { (this.__DomSanitizer_63 = new import54.DomSanitizerImpl()); }
    return this.__DomSanitizer_63;
  }
  get _Sanitizer_64():any {
    if ((this.__Sanitizer_64 == null)) { (this.__Sanitizer_64 = this._DomSanitizer_63); }
    return this.__Sanitizer_64;
  }
  get _AnimationQueue_65():import55.AnimationQueue {
    if ((this.__AnimationQueue_65 == null)) { (this.__AnimationQueue_65 = new import55.AnimationQueue(this.parent.get(import91.NgZone))); }
    return this.__AnimationQueue_65;
  }
  get _ViewUtils_66():import56.ViewUtils {
    if ((this.__ViewUtils_66 == null)) { (this.__ViewUtils_66 = new import56.ViewUtils(this._RootRenderer_62,this._Sanitizer_64,this._AnimationQueue_65)); }
    return this.__ViewUtils_66;
  }
  get _IterableDiffers_67():any {
    if ((this.__IterableDiffers_67 == null)) { (this.__IterableDiffers_67 = import3._iterableDiffersFactory()); }
    return this.__IterableDiffers_67;
  }
  get _KeyValueDiffers_68():any {
    if ((this.__KeyValueDiffers_68 == null)) { (this.__KeyValueDiffers_68 = import3._keyValueDiffersFactory()); }
    return this.__KeyValueDiffers_68;
  }
  get _SharedStylesHost_69():any {
    if ((this.__SharedStylesHost_69 == null)) { (this.__SharedStylesHost_69 = this._DomSharedStylesHost_58); }
    return this.__SharedStylesHost_69;
  }
  get _Title_70():import57.Title {
    if ((this.__Title_70 == null)) { (this.__Title_70 = new import57.Title()); }
    return this.__Title_70;
  }
  get _RadioControlRegistry_71():import58.RadioControlRegistry {
    if ((this.__RadioControlRegistry_71 == null)) { (this.__RadioControlRegistry_71 = new import58.RadioControlRegistry()); }
    return this.__RadioControlRegistry_71;
  }
  get _BrowserXhr_72():import59.BrowserXhr {
    if ((this.__BrowserXhr_72 == null)) { (this.__BrowserXhr_72 = new import59.BrowserXhr()); }
    return this.__BrowserXhr_72;
  }
  get _ResponseOptions_73():import60.BaseResponseOptions {
    if ((this.__ResponseOptions_73 == null)) { (this.__ResponseOptions_73 = new import60.BaseResponseOptions()); }
    return this.__ResponseOptions_73;
  }
  get _XSRFStrategy_74():any {
    if ((this.__XSRFStrategy_74 == null)) { (this.__XSRFStrategy_74 = import7._createDefaultCookieXSRFStrategy()); }
    return this.__XSRFStrategy_74;
  }
  get _XHRBackend_75():import61.XHRBackend {
    if ((this.__XHRBackend_75 == null)) { (this.__XHRBackend_75 = new import61.XHRBackend(this._BrowserXhr_72,this._ResponseOptions_73,this._XSRFStrategy_74)); }
    return this.__XHRBackend_75;
  }
  get _RequestOptions_76():import62.BaseRequestOptions {
    if ((this.__RequestOptions_76 == null)) { (this.__RequestOptions_76 = new import62.BaseRequestOptions()); }
    return this.__RequestOptions_76;
  }
  get _Http_77():any {
    if ((this.__Http_77 == null)) { (this.__Http_77 = import7.httpFactory(this._XHRBackend_75,this._RequestOptions_76)); }
    return this.__Http_77;
  }
  get _MATERIAL_COMPATIBILITY_MODE_78():any {
    if ((this.__MATERIAL_COMPATIBILITY_MODE_78 == null)) { (this.__MATERIAL_COMPATIBILITY_MODE_78 = false); }
    return this.__MATERIAL_COMPATIBILITY_MODE_78;
  }
  get _ViewportRuler_79():any {
    if ((this.__ViewportRuler_79 == null)) { (this.__ViewportRuler_79 = import93.VIEWPORT_RULER_PROVIDER_FACTORY(this.parent.get(import93.ViewportRuler,(null as any)))); }
    return this.__ViewportRuler_79;
  }
  get _OverlayContainer_80():any {
    if ((this.__OverlayContainer_80 == null)) { (this.__OverlayContainer_80 = import94.OVERLAY_CONTAINER_PROVIDER_FACTORY(this.parent.get(import94.OverlayContainer,(null as any)))); }
    return this.__OverlayContainer_80;
  }
  get _OverlayPositionBuilder_81():import63.OverlayPositionBuilder {
    if ((this.__OverlayPositionBuilder_81 == null)) { (this.__OverlayPositionBuilder_81 = new import63.OverlayPositionBuilder(this._ViewportRuler_79)); }
    return this.__OverlayPositionBuilder_81;
  }
  get _Overlay_82():import64.Overlay {
    if ((this.__Overlay_82 == null)) { (this.__Overlay_82 = new import64.Overlay(this._OverlayContainer_80,this,this._OverlayPositionBuilder_81,this._ApplicationRef_51,this,this.parent.get(import91.NgZone))); }
    return this.__Overlay_82;
  }
  get _ScrollDispatcher_83():any {
    if ((this.__ScrollDispatcher_83 == null)) { (this.__ScrollDispatcher_83 = import95.SCROLL_DISPATCHER_PROVIDER_FACTORY(this.parent.get(import95.ScrollDispatcher,(null as any)))); }
    return this.__ScrollDispatcher_83;
  }
  get _Platform_84():import65.Platform {
    if ((this.__Platform_84 == null)) { (this.__Platform_84 = new import65.Platform()); }
    return this.__Platform_84;
  }
  get _InteractivityChecker_85():import66.InteractivityChecker {
    if ((this.__InteractivityChecker_85 == null)) { (this.__InteractivityChecker_85 = new import66.InteractivityChecker(this._Platform_84)); }
    return this.__InteractivityChecker_85;
  }
  get _LiveAnnouncer_86():any {
    if ((this.__LiveAnnouncer_86 == null)) { (this.__LiveAnnouncer_86 = import96.LIVE_ANNOUNCER_PROVIDER_FACTORY(this.parent.get(import96.LiveAnnouncer,(null as any)),this.parent.get(import96.LIVE_ANNOUNCER_ELEMENT_TOKEN,(null as any)))); }
    return this.__LiveAnnouncer_86;
  }
  get _DomProjection_87():import31.DomProjection {
    if ((this.__DomProjection_87 == null)) { (this.__DomProjection_87 = new import31.DomProjection()); }
    return this.__DomProjection_87;
  }
  get _UniqueSelectionDispatcher_88():any {
    if ((this.__UniqueSelectionDispatcher_88 == null)) { (this.__UniqueSelectionDispatcher_88 = import97.UNIQUE_SELECTION_DISPATCHER_PROVIDER_FACTORY(this.parent.get(import97.UniqueSelectionDispatcher,(null as any)))); }
    return this.__UniqueSelectionDispatcher_88;
  }
  get _MdDialog_89():import67.MdDialog {
    if ((this.__MdDialog_89 == null)) { (this.__MdDialog_89 = new import67.MdDialog(this._Overlay_82,this,this.parent.get(import67.MdDialog,(null as any)))); }
    return this.__MdDialog_89;
  }
  get _MdIconRegistry_90():any {
    if ((this.__MdIconRegistry_90 == null)) { (this.__MdIconRegistry_90 = import35.ICON_REGISTRY_PROVIDER_FACTORY(this.parent.get(import98.MdIconRegistry,(null as any)),this._Http_77,this._DomSanitizer_63)); }
    return this.__MdIconRegistry_90;
  }
  get _MdSnackBar_91():import40.MdSnackBar {
    if ((this.__MdSnackBar_91 == null)) { (this.__MdSnackBar_91 = new import40.MdSnackBar(this._Overlay_82,this._LiveAnnouncer_86,this.parent.get(import40.MdSnackBar,(null as any)))); }
    return this.__MdSnackBar_91;
  }
  get _ROUTER_CONFIGURATION_92():any {
    if ((this.__ROUTER_CONFIGURATION_92 == null)) { (this.__ROUTER_CONFIGURATION_92 = {}); }
    return this.__ROUTER_CONFIGURATION_92;
  }
  get _LocationStrategy_93():any {
    if ((this.__LocationStrategy_93 == null)) { (this.__LocationStrategy_93 = import43.provideLocationStrategy(this.parent.get(import99.PlatformLocation),this.parent.get(import100.APP_BASE_HREF,(null as any)),this._ROUTER_CONFIGURATION_92)); }
    return this.__LocationStrategy_93;
  }
  get _Location_94():import68.Location {
    if ((this.__Location_94 == null)) { (this.__Location_94 = new import68.Location(this._LocationStrategy_93)); }
    return this.__Location_94;
  }
  get _UrlSerializer_95():import69.DefaultUrlSerializer {
    if ((this.__UrlSerializer_95 == null)) { (this.__UrlSerializer_95 = new import69.DefaultUrlSerializer()); }
    return this.__UrlSerializer_95;
  }
  get _RouterOutletMap_96():import70.RouterOutletMap {
    if ((this.__RouterOutletMap_96 == null)) { (this.__RouterOutletMap_96 = new import70.RouterOutletMap()); }
    return this.__RouterOutletMap_96;
  }
  get _NgModuleFactoryLoader_97():import71.SystemJsNgModuleLoader {
    if ((this.__NgModuleFactoryLoader_97 == null)) { (this.__NgModuleFactoryLoader_97 = new import71.SystemJsNgModuleLoader(this._Compiler_52,this.parent.get(import71.SystemJsNgModuleLoaderConfig,(null as any)))); }
    return this.__NgModuleFactoryLoader_97;
  }
  get _ROUTES_98():any[] {
      if ((this.__ROUTES_98 == null)) { (this.__ROUTES_98 = [[
        {
          path: 'app',
          component: import101.AppComponent
        }
        ,
        {
          path: 'home',
          component: import102.HomeComponent
        }
        ,
        {
          path: 'take-quiz/:id',
          component: import103.TakeQuizComponent
        }
        ,
        {
          path: 'dashboard',
          component: import104.DashboardComponent,
          canActivate: [import74.AuthGuard]
        }
        ,
        {
          path: 'quizes',
          component: import105.QuizesComponent,
          canActivate: [import74.AuthGuard]
        }
        ,
        {
          path: '',
          redirectTo: '/home',
          pathMatch: 'full'
        }
        ,
        {
          path: '**',
          redirectTo: '/home'
        }

      ]
    ]); }
    return this.__ROUTES_98;
  }
  get _Router_99():any {
    if ((this.__Router_99 == null)) { (this.__Router_99 = import43.setupRouter(this._ApplicationRef_51,this._UrlSerializer_95,this._RouterOutletMap_96,this._Location_94,this,this._NgModuleFactoryLoader_97,this._Compiler_52,this._ROUTES_98,this._ROUTER_CONFIGURATION_92,this.parent.get(import106.UrlHandlingStrategy,(null as any)),this.parent.get(import107.RouteReuseStrategy,(null as any)))); }
    return this.__Router_99;
  }
  get _ActivatedRoute_100():any {
    if ((this.__ActivatedRoute_100 == null)) { (this.__ActivatedRoute_100 = import43.rootRoute(this._Router_99)); }
    return this.__ActivatedRoute_100;
  }
  get _PreloadAllModules_104():import72.PreloadAllModules {
    if ((this.__PreloadAllModules_104 == null)) { (this.__PreloadAllModules_104 = new import72.PreloadAllModules()); }
    return this.__PreloadAllModules_104;
  }
  get _ROUTER_INITIALIZER_105():any {
    if ((this.__ROUTER_INITIALIZER_105 == null)) { (this.__ROUTER_INITIALIZER_105 = import43.initialRouterNavigation(this._Router_99,this._ApplicationRef_51,this._RouterPreloader_103,this._ROUTER_CONFIGURATION_92)); }
    return this.__ROUTER_INITIALIZER_105;
  }
  get _APP_BOOTSTRAP_LISTENER_106():any[] {
    if ((this.__APP_BOOTSTRAP_LISTENER_106 == null)) { (this.__APP_BOOTSTRAP_LISTENER_106 = [this._ROUTER_INITIALIZER_105]); }
    return this.__APP_BOOTSTRAP_LISTENER_106;
  }
  get _AuthenticationService_107():import73.AuthenticationService {
    if ((this.__AuthenticationService_107 == null)) { (this.__AuthenticationService_107 = new import73.AuthenticationService(this._Http_77)); }
    return this.__AuthenticationService_107;
  }
  get _AuthGuard_108():import74.AuthGuard {
    if ((this.__AuthGuard_108 == null)) { (this.__AuthGuard_108 = new import74.AuthGuard(this._Router_99,this._AuthenticationService_107)); }
    return this.__AuthGuard_108;
  }
  get _DataService_109():import75.DataService {
    if ((this.__DataService_109 == null)) { (this.__DataService_109 = new import75.DataService(this._Http_77)); }
    return this.__DataService_109;
  }
  createInternal():import1.AppModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ApplicationModule_1 = new import3.ApplicationModule();
    this._BrowserModule_2 = new import4.BrowserModule(this.parent.get(import4.BrowserModule,(null as any)));
    this._InternalFormsSharedModule_3 = new import5.InternalFormsSharedModule();
    this._FormsModule_4 = new import6.FormsModule();
    this._HttpModule_5 = new import7.HttpModule();
    this._DefaultStyleCompatibilityModeModule_6 = new import8.DefaultStyleCompatibilityModeModule();
    this._MdRippleModule_7 = new import9.MdRippleModule();
    this._MdOptionModule_8 = new import10.MdOptionModule();
    this._PortalModule_9 = new import11.PortalModule();
    this._OverlayModule_10 = new import12.OverlayModule();
    this._MdAutocompleteModule_11 = new import13.MdAutocompleteModule();
    this._MdButtonModule_12 = new import14.MdButtonModule();
    this._MdCardModule_13 = new import15.MdCardModule();
    this._MdChipsModule_14 = new import16.MdChipsModule();
    this._MdCheckboxModule_15 = new import17.MdCheckboxModule();
    this._MdLineModule_16 = new import18.MdLineModule();
    this._MdGridListModule_17 = new import19.MdGridListModule();
    this._PlatformModule_18 = new import20.PlatformModule();
    this._MdInputModule_19 = new import21.MdInputModule();
    this._MdListModule_20 = new import22.MdListModule();
    this._MdProgressBarModule_21 = new import23.MdProgressBarModule();
    this._MdProgressSpinnerModule_22 = new import24.MdProgressSpinnerModule();
    this._MdSelectModule_23 = new import25.MdSelectModule();
    this._A11yModule_24 = new import26.A11yModule();
    this._MdSidenavModule_25 = new import27.MdSidenavModule();
    this._ObserveContentModule_26 = new import28.ObserveContentModule();
    this._MdTabsModule_27 = new import29.MdTabsModule();
    this._MdToolbarModule_28 = new import30.MdToolbarModule();
    this._ProjectionModule_29 = new import31.ProjectionModule();
    this._RtlModule_30 = new import32.RtlModule();
    this._MdButtonToggleModule_31 = new import33.MdButtonToggleModule();
    this._MdDialogModule_32 = new import34.MdDialogModule();
    this._MdIconModule_33 = new import35.MdIconModule();
    this._MdMenuModule_34 = new import36.MdMenuModule();
    this._MdRadioModule_35 = new import37.MdRadioModule();
    this._MdSliderModule_36 = new import38.MdSliderModule();
    this._MdSlideToggleModule_37 = new import39.MdSlideToggleModule();
    this._MdSnackBarModule_38 = new import40.MdSnackBarModule();
    this._MdTooltipModule_39 = new import41.MdTooltipModule();
    this._MaterialRootModule_40 = new import42.MaterialRootModule();
    this._ROUTER_FORROOT_GUARD_41 = import43.provideForRootGuard(this.parent.get(import108.Router,(null as any)));
    this._RouterModule_42 = new import43.RouterModule(this._ROUTER_FORROOT_GUARD_41);
    this._AppRoutingModule_43 = new import44.AppRoutingModule();
    this._AppModule_44 = new import1.AppModule();
    this._ErrorHandler_47 = import4.errorHandler();
    this._ApplicationInitStatus_48 = new import46.ApplicationInitStatus(this.parent.get(import46.APP_INITIALIZER,(null as any)));
    this._Testability_49 = new import47.Testability(this.parent.get(import91.NgZone));
    this._ApplicationRef__50 = new import48.ApplicationRef_(this.parent.get(import91.NgZone),this.parent.get(import109.Console),this,this._ErrorHandler_47,this,this._ApplicationInitStatus_48,this.parent.get(import47.TestabilityRegistry,(null as any)),this._Testability_49);
    this._NoPreloading_101 = new import72.NoPreloading();
    this._PreloadingStrategy_102 = this._NoPreloading_101;
    this._RouterPreloader_103 = new import72.RouterPreloader(this._Router_99,this._NgModuleFactoryLoader_97,this._Compiler_52,this,this._PreloadingStrategy_102);
    return this._AppModule_44;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.ApplicationModule)) { return this._ApplicationModule_1; }
    if ((token === import4.BrowserModule)) { return this._BrowserModule_2; }
    if ((token === import5.InternalFormsSharedModule)) { return this._InternalFormsSharedModule_3; }
    if ((token === import6.FormsModule)) { return this._FormsModule_4; }
    if ((token === import7.HttpModule)) { return this._HttpModule_5; }
    if ((token === import8.DefaultStyleCompatibilityModeModule)) { return this._DefaultStyleCompatibilityModeModule_6; }
    if ((token === import9.MdRippleModule)) { return this._MdRippleModule_7; }
    if ((token === import10.MdOptionModule)) { return this._MdOptionModule_8; }
    if ((token === import11.PortalModule)) { return this._PortalModule_9; }
    if ((token === import12.OverlayModule)) { return this._OverlayModule_10; }
    if ((token === import13.MdAutocompleteModule)) { return this._MdAutocompleteModule_11; }
    if ((token === import14.MdButtonModule)) { return this._MdButtonModule_12; }
    if ((token === import15.MdCardModule)) { return this._MdCardModule_13; }
    if ((token === import16.MdChipsModule)) { return this._MdChipsModule_14; }
    if ((token === import17.MdCheckboxModule)) { return this._MdCheckboxModule_15; }
    if ((token === import18.MdLineModule)) { return this._MdLineModule_16; }
    if ((token === import19.MdGridListModule)) { return this._MdGridListModule_17; }
    if ((token === import20.PlatformModule)) { return this._PlatformModule_18; }
    if ((token === import21.MdInputModule)) { return this._MdInputModule_19; }
    if ((token === import22.MdListModule)) { return this._MdListModule_20; }
    if ((token === import23.MdProgressBarModule)) { return this._MdProgressBarModule_21; }
    if ((token === import24.MdProgressSpinnerModule)) { return this._MdProgressSpinnerModule_22; }
    if ((token === import25.MdSelectModule)) { return this._MdSelectModule_23; }
    if ((token === import26.A11yModule)) { return this._A11yModule_24; }
    if ((token === import27.MdSidenavModule)) { return this._MdSidenavModule_25; }
    if ((token === import28.ObserveContentModule)) { return this._ObserveContentModule_26; }
    if ((token === import29.MdTabsModule)) { return this._MdTabsModule_27; }
    if ((token === import30.MdToolbarModule)) { return this._MdToolbarModule_28; }
    if ((token === import31.ProjectionModule)) { return this._ProjectionModule_29; }
    if ((token === import32.RtlModule)) { return this._RtlModule_30; }
    if ((token === import33.MdButtonToggleModule)) { return this._MdButtonToggleModule_31; }
    if ((token === import34.MdDialogModule)) { return this._MdDialogModule_32; }
    if ((token === import35.MdIconModule)) { return this._MdIconModule_33; }
    if ((token === import36.MdMenuModule)) { return this._MdMenuModule_34; }
    if ((token === import37.MdRadioModule)) { return this._MdRadioModule_35; }
    if ((token === import38.MdSliderModule)) { return this._MdSliderModule_36; }
    if ((token === import39.MdSlideToggleModule)) { return this._MdSlideToggleModule_37; }
    if ((token === import40.MdSnackBarModule)) { return this._MdSnackBarModule_38; }
    if ((token === import41.MdTooltipModule)) { return this._MdTooltipModule_39; }
    if ((token === import42.MaterialRootModule)) { return this._MaterialRootModule_40; }
    if ((token === import43.ROUTER_FORROOT_GUARD)) { return this._ROUTER_FORROOT_GUARD_41; }
    if ((token === import43.RouterModule)) { return this._RouterModule_42; }
    if ((token === import44.AppRoutingModule)) { return this._AppRoutingModule_43; }
    if ((token === import1.AppModule)) { return this._AppModule_44; }
    if ((token === import86.LOCALE_ID)) { return this._LOCALE_ID_45; }
    if ((token === import45.NgLocalization)) { return this._NgLocalization_46; }
    if ((token === import110.ErrorHandler)) { return this._ErrorHandler_47; }
    if ((token === import46.ApplicationInitStatus)) { return this._ApplicationInitStatus_48; }
    if ((token === import47.Testability)) { return this._Testability_49; }
    if ((token === import48.ApplicationRef_)) { return this._ApplicationRef__50; }
    if ((token === import48.ApplicationRef)) { return this._ApplicationRef_51; }
    if ((token === import49.Compiler)) { return this._Compiler_52; }
    if ((token === import87.APP_ID)) { return this._APP_ID_53; }
    if ((token === import111.DOCUMENT)) { return this._DOCUMENT_54; }
    if ((token === import90.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_55; }
    if ((token === import51.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_56; }
    if ((token === import51.EventManager)) { return this._EventManager_57; }
    if ((token === import52.DomSharedStylesHost)) { return this._DomSharedStylesHost_58; }
    if ((token === import112.AnimationDriver)) { return this._AnimationDriver_59; }
    if ((token === import53.DomRootRenderer)) { return this._DomRootRenderer_60; }
    if ((token === import48.NgProbeToken)) { return this._NgProbeToken_61; }
    if ((token === import113.RootRenderer)) { return this._RootRenderer_62; }
    if ((token === import54.DomSanitizer)) { return this._DomSanitizer_63; }
    if ((token === import114.Sanitizer)) { return this._Sanitizer_64; }
    if ((token === import55.AnimationQueue)) { return this._AnimationQueue_65; }
    if ((token === import56.ViewUtils)) { return this._ViewUtils_66; }
    if ((token === import115.IterableDiffers)) { return this._IterableDiffers_67; }
    if ((token === import116.KeyValueDiffers)) { return this._KeyValueDiffers_68; }
    if ((token === import52.SharedStylesHost)) { return this._SharedStylesHost_69; }
    if ((token === import57.Title)) { return this._Title_70; }
    if ((token === import58.RadioControlRegistry)) { return this._RadioControlRegistry_71; }
    if ((token === import59.BrowserXhr)) { return this._BrowserXhr_72; }
    if ((token === import60.ResponseOptions)) { return this._ResponseOptions_73; }
    if ((token === import117.XSRFStrategy)) { return this._XSRFStrategy_74; }
    if ((token === import61.XHRBackend)) { return this._XHRBackend_75; }
    if ((token === import62.RequestOptions)) { return this._RequestOptions_76; }
    if ((token === import118.Http)) { return this._Http_77; }
    if ((token === import8.MATERIAL_COMPATIBILITY_MODE)) { return this._MATERIAL_COMPATIBILITY_MODE_78; }
    if ((token === import93.ViewportRuler)) { return this._ViewportRuler_79; }
    if ((token === import94.OverlayContainer)) { return this._OverlayContainer_80; }
    if ((token === import63.OverlayPositionBuilder)) { return this._OverlayPositionBuilder_81; }
    if ((token === import64.Overlay)) { return this._Overlay_82; }
    if ((token === import95.ScrollDispatcher)) { return this._ScrollDispatcher_83; }
    if ((token === import65.Platform)) { return this._Platform_84; }
    if ((token === import66.InteractivityChecker)) { return this._InteractivityChecker_85; }
    if ((token === import96.LiveAnnouncer)) { return this._LiveAnnouncer_86; }
    if ((token === import31.DomProjection)) { return this._DomProjection_87; }
    if ((token === import97.UniqueSelectionDispatcher)) { return this._UniqueSelectionDispatcher_88; }
    if ((token === import67.MdDialog)) { return this._MdDialog_89; }
    if ((token === import98.MdIconRegistry)) { return this._MdIconRegistry_90; }
    if ((token === import40.MdSnackBar)) { return this._MdSnackBar_91; }
    if ((token === import43.ROUTER_CONFIGURATION)) { return this._ROUTER_CONFIGURATION_92; }
    if ((token === import100.LocationStrategy)) { return this._LocationStrategy_93; }
    if ((token === import68.Location)) { return this._Location_94; }
    if ((token === import69.UrlSerializer)) { return this._UrlSerializer_95; }
    if ((token === import70.RouterOutletMap)) { return this._RouterOutletMap_96; }
    if ((token === import119.NgModuleFactoryLoader)) { return this._NgModuleFactoryLoader_97; }
    if ((token === import120.ROUTES)) { return this._ROUTES_98; }
    if ((token === import108.Router)) { return this._Router_99; }
    if ((token === import121.ActivatedRoute)) { return this._ActivatedRoute_100; }
    if ((token === import72.NoPreloading)) { return this._NoPreloading_101; }
    if ((token === import72.PreloadingStrategy)) { return this._PreloadingStrategy_102; }
    if ((token === import72.RouterPreloader)) { return this._RouterPreloader_103; }
    if ((token === import72.PreloadAllModules)) { return this._PreloadAllModules_104; }
    if ((token === import43.ROUTER_INITIALIZER)) { return this._ROUTER_INITIALIZER_105; }
    if ((token === import87.APP_BOOTSTRAP_LISTENER)) { return this._APP_BOOTSTRAP_LISTENER_106; }
    if ((token === import73.AuthenticationService)) { return this._AuthenticationService_107; }
    if ((token === import74.AuthGuard)) { return this._AuthGuard_108; }
    if ((token === import75.DataService)) { return this._DataService_109; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ApplicationRef__50.ngOnDestroy();
    this._RouterPreloader_103.ngOnDestroy();
  }
}
export const AppModuleNgFactory:import0.NgModuleFactory<import1.AppModule> = new import0.NgModuleFactory(AppModuleInjector,import1.AppModule);