language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 1.0.0-preview2-003121
install:
  - export DOTNET_INSTALL_DIR="$PWD/.dotnetsdk"
  - curl -sSL https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0/scripts/obtain/dotnet-install.sh | bash /dev/stdin --version "$CLI_VERSION" --install-dir "$DOTNET_INSTALL_DIR"
  - export PATH="$DOTNET_INSTALL_DIR:$PATH"  
before_script:
  - chmod a+x ./ApiQuizGenerator/build.sh 
script:
  - ./ApiQuizGenerator/build.sh --quiet verify