language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 1.0.0-preview2-003121
addons:
  apt:
    sources:
    - sourceline: 'deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ trusty main'
      key_url: 'https://apt-mo.trafficmanager.net/keys/microsoft.asc'
    packages:
    - dotnet-dev-1.0.1
install:
  - export DOTNET_CLI_TELEMETRY_OPTOUT=1
before_script:
  - chmod a+x ./ApiQuizGenerator/build.sh 
script:
  - ./ApiQuizGenerator/build.sh --quiet verify