/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../app/components/dashboard.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '../../../app/services/authentication.service';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/constants';
import * as import8 from '@angular/core/src/linker/component_factory';
import * as import9 from '@angular/http/src/http';
import * as import10 from '../../../app/components/navigation.component';
import * as import11 from './navigation.component.ngfactory';
import * as import12 from '@angular/core/src/linker/view_container';
import * as import13 from '../../node_modules/@angular/router/src/directives/router_outlet.ngfactory';
import * as import14 from '@angular/material/button/button';
import * as import15 from '../../node_modules/@angular/material/button/button.ngfactory';
import * as import16 from '@angular/core/src/change_detection/change_detection_util';
import * as import17 from '@angular/router/src/router';
import * as import18 from '@angular/router/src/router_outlet_map';
import * as import19 from '@angular/core/src/linker/component_factory_resolver';
import * as import20 from '@angular/core/src/linker/element_ref';
import * as import21 from '@angular/router/src/directives/router_outlet';
import * as import22 from '../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import23 from '@angular/core/src/linker/template_ref';
import * as import24 from '@angular/common/src/directives/ng_if';
export class Wrapper_DashboardComponent {
  /*private*/ _eventHandler:Function;
  context:import0.DashboardComponent;
  /*private*/ _changed:boolean;
  constructor(p0:any) {
    this._changed = false;
    this.context = new import0.DashboardComponent(p0);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_DashboardComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_DashboardComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.DashboardComponent>;
  _AuthenticationService_0_3:import5.AuthenticationService;
  _DashboardComponent_0_4:Wrapper_DashboardComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_DashboardComponent_Host0,renderType_DashboardComponent_Host,import6.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'ng-component',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_DashboardComponent0(this.viewUtils,this,0,this._el_0);
    this._AuthenticationService_0_3 = new import5.AuthenticationService(this.injectorGet(import9.Http,this.parentIndex));
    this._DashboardComponent_0_4 = new Wrapper_DashboardComponent(this._AuthenticationService_0_3);
    this.compView_0.create(this._DashboardComponent_0_4.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import8.ComponentRef_<any>(0,this,this._el_0,this._DashboardComponent_0_4.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import5.AuthenticationService) && (0 === requestNodeIndex))) { return this._AuthenticationService_0_3; }
    if (((token === import0.DashboardComponent) && (0 === requestNodeIndex))) { return this._DashboardComponent_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._DashboardComponent_0_4.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const DashboardComponentNgFactory:import8.ComponentFactory<import0.DashboardComponent> = new import8.ComponentFactory<import0.DashboardComponent>('ng-component',View_DashboardComponent_Host0,import0.DashboardComponent);
const styles_DashboardComponent:any[] = ([] as any[]);
class View_DashboardComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  compView_4:import1.AppView<import10.NavigationComponent>;
  _AuthenticationService_4_3:import5.AuthenticationService;
  _NavigationComponent_4_4:import11.Wrapper_NavigationComponent;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _text_13:any;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _text_17:any;
  _el_18:any;
  _text_19:any;
  _text_20:any;
  _el_21:any;
  _text_22:any;
  _el_23:any;
  /*private*/ _vc_23:import12.ViewContainer;
  _RouterOutlet_23_5:import13.Wrapper_RouterOutlet;
  _text_24:any;
  _el_25:any;
  _text_26:any;
  _el_27:any;
  _text_28:any;
  _text_29:any;
  _text_30:any;
  _el_31:any;
  _text_32:any;
  _el_33:any;
  compView_33:import1.AppView<import14.MdButton>;
  _MdButton_33_3:import15.Wrapper_MdButton;
  _text_34:any;
  _text_35:any;
  _text_36:any;
  _text_37:any;
  _el_38:any;
  _text_39:any;
  _el_40:any;
  _text_41:any;
  _el_42:any;
  _text_43:any;
  _text_44:any;
  _text_45:any;
  _el_46:any;
  _text_47:any;
  _el_48:any;
  compView_48:import1.AppView<import14.MdButton>;
  _MdButton_48_3:import15.Wrapper_MdButton;
  _text_49:any;
  _text_50:any;
  _text_51:any;
  _text_52:any;
  _text_53:any;
  /*private*/ _expr_63:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import12.ViewContainer) {
    super(View_DashboardComponent1,renderType_DashboardComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_63 = import16.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'class','row main'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','col-sm-3 col-xs-12 left'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n       ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'app-navigation',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_4 = new import11.View_NavigationComponent0(this.viewUtils,this,4,this._el_4);
    this._AuthenticationService_4_3 = new import5.AuthenticationService(this.parentView.injectorGet(import9.Http,this.parentIndex));
    this._NavigationComponent_4_4 = new import11.Wrapper_NavigationComponent(this._AuthenticationService_4_3,this.parentView.injectorGet(import17.Router,this.parentIndex));
    this.compView_4.create(this._NavigationComponent_4_4.context);
    this._text_5 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_6 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_7 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','col-sm-9 col-xs-12 right'),(null as any));
    this._text_8 = this.renderer.createText(this._el_7,'\n        ',(null as any));
    this._el_9 = import3.createRenderElement(this.renderer,this._el_7,'div',new import3.InlineArray2(2,'class','right user-info'),(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'\n            ',(null as any));
    this._el_11 = import3.createRenderElement(this.renderer,this._el_9,'a',new import3.InlineArray2(2,'href','#'),(null as any));
    this._text_12 = this.renderer.createText(this._el_11,'',(null as any));
    this._text_13 = this.renderer.createText(this._el_9,'\n        ',(null as any));
    this._text_14 = this.renderer.createText(this._el_7,'\n        ',(null as any));
    this._el_15 = import3.createRenderElement(this.renderer,this._el_7,'h3',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_16 = this.renderer.createText(this._el_15,'Welcome to Quiz-O-Matic!',(null as any));
    this._text_17 = this.renderer.createText(this._el_7,'\n\n        ',(null as any));
    this._el_18 = import3.createRenderElement(this.renderer,this._el_7,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_19 = this.renderer.createText(this._el_18,'Select an option below to take or create a quiz:',(null as any));
    this._text_20 = this.renderer.createText(this._el_7,'    \n        ',(null as any));
    this._el_21 = import3.createRenderElement(this.renderer,this._el_7,'div',new import3.InlineArray2(2,'class','col-xs-12 section'),(null as any));
    this._text_22 = this.renderer.createText(this._el_21,'  \n            ',(null as any));
    this._el_23 = import3.createRenderElement(this.renderer,this._el_21,'router-outlet',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._vc_23 = new import12.ViewContainer(23,21,this,this._el_23);
    this._RouterOutlet_23_5 = new import13.Wrapper_RouterOutlet(this.parentView.injectorGet(import18.RouterOutletMap,this.parentIndex),this._vc_23.vcRef,this.parentView.injectorGet(import19.ComponentFactoryResolver,this.parentIndex),(null as any));
    this._text_24 = this.renderer.createText(this._el_21,'            \n            ',(null as any));
    this._el_25 = import3.createRenderElement(this.renderer,this._el_21,'div',new import3.InlineArray2(2,'class','col-sm-6 col-xs-12'),(null as any));
    this._text_26 = this.renderer.createText(this._el_25,'\n                ',(null as any));
    this._el_27 = import3.createRenderElement(this.renderer,this._el_25,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_28 = this.renderer.createText(this._el_27,'Quiz-O-Matic allows you to create a quiz or "would you rather" which you can share with your friends and the internet.',(null as any));
    this._text_29 = this.renderer.createText(this._el_25,'\n            ',(null as any));
    this._text_30 = this.renderer.createText(this._el_21,'\n            ',(null as any));
    this._el_31 = import3.createRenderElement(this.renderer,this._el_21,'div',new import3.InlineArray2(2,'class','col-sm-6 col-xs-12'),(null as any));
    this._text_32 = this.renderer.createText(this._el_31,'\n                ',(null as any));
    this._el_33 = import3.createRenderElement(this.renderer,this._el_31,'button',new import3.InlineArray8(8,'button','','class','primaryButton center','color','primary','md-raised-button',''),(null as any));
    this.compView_33 = new import15.View_MdButton0(this.viewUtils,this,33,this._el_33);
    this._MdButton_33_3 = new import15.Wrapper_MdButton(new import20.ElementRef(this._el_33),this.renderer);
    this._text_34 = this.renderer.createText((null as any),'Create a Quiz',(null as any));
    this.compView_33.create(this._MdButton_33_3.context);
    this._text_35 = this.renderer.createText(this._el_31,'\n            ',(null as any));
    this._text_36 = this.renderer.createText(this._el_21,'          \n        ',(null as any));
    this._text_37 = this.renderer.createText(this._el_7,'    \n        ',(null as any));
    this._el_38 = import3.createRenderElement(this.renderer,this._el_7,'div',new import3.InlineArray2(2,'class','col-xs-12 section'),(null as any));
    this._text_39 = this.renderer.createText(this._el_38,'\n            ',(null as any));
    this._el_40 = import3.createRenderElement(this.renderer,this._el_38,'div',new import3.InlineArray2(2,'class','col-sm-6 col-xs-12'),(null as any));
    this._text_41 = this.renderer.createText(this._el_40,'\n            ',(null as any));
    this._el_42 = import3.createRenderElement(this.renderer,this._el_40,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_43 = this.renderer.createText(this._el_42,'Browse through and take different quizes others have create.',(null as any));
    this._text_44 = this.renderer.createText(this._el_40,'\n            ',(null as any));
    this._text_45 = this.renderer.createText(this._el_38,'\n                ',(null as any));
    this._el_46 = import3.createRenderElement(this.renderer,this._el_38,'div',new import3.InlineArray2(2,'class','col-sm-6 col-xs-12'),(null as any));
    this._text_47 = this.renderer.createText(this._el_46,'\n                    ',(null as any));
    this._el_48 = import3.createRenderElement(this.renderer,this._el_46,'button',new import3.InlineArray8(8,'button','','class','primaryButton center','color','primary','md-raised-button',''),(null as any));
    this.compView_48 = new import15.View_MdButton0(this.viewUtils,this,48,this._el_48);
    this._MdButton_48_3 = new import15.Wrapper_MdButton(new import20.ElementRef(this._el_48),this.renderer);
    this._text_49 = this.renderer.createText((null as any),'Take a Quiz',(null as any));
    this.compView_48.create(this._MdButton_48_3.context);
    this._text_50 = this.renderer.createText(this._el_46,'        \n            ',(null as any));
    this._text_51 = this.renderer.createText(this._el_38,'\n        ',(null as any));
    this._text_52 = this.renderer.createText(this._el_7,'\n    ',(null as any));
    this._text_53 = this.renderer.createText(this._el_0,'\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_33,new import3.InlineArray8(6,'mousedown',(null as any),'focus',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_33));
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_48,new import3.InlineArray8(6,'mousedown',(null as any),'focus',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_48));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._text_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._text_35,
      this._text_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._el_40,
      this._text_41,
      this._el_42,
      this._text_43,
      this._text_44,
      this._text_45,
      this._el_46,
      this._text_47,
      this._el_48,
      this._text_49,
      this._text_50,
      this._text_51,
      this._text_52,
      this._text_53
    ]
    ),[
      disposable_0,
      disposable_1
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import5.AuthenticationService) && (4 === requestNodeIndex))) { return this._AuthenticationService_4_3; }
    if (((token === import10.NavigationComponent) && (4 === requestNodeIndex))) { return this._NavigationComponent_4_4.context; }
    if (((token === import21.RouterOutlet) && (23 === requestNodeIndex))) { return this._RouterOutlet_23_5.context; }
    if (((token === import14.MdButton) && ((33 <= requestNodeIndex) && (requestNodeIndex <= 34)))) { return this._MdButton_33_3.context; }
    if (((token === import14.MdButton) && ((48 <= requestNodeIndex) && (requestNodeIndex <= 49)))) { return this._MdButton_48_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._NavigationComponent_4_4.ngDoCheck(this,this._el_4,throwOnChange);
    this._RouterOutlet_23_5.ngDoCheck(this,this._el_23,throwOnChange);
    const currVal_33_0_0:any = 'primary';
    this._MdButton_33_3.check_color(currVal_33_0_0,throwOnChange,false);
    if (this._MdButton_33_3.ngDoCheck(this,this._el_33,throwOnChange)) { this.compView_33.markAsCheckOnce(); }
    const currVal_48_0_0:any = 'primary';
    this._MdButton_48_3.check_color(currVal_48_0_0,throwOnChange,false);
    if (this._MdButton_48_3.ngDoCheck(this,this._el_48,throwOnChange)) { this.compView_48.markAsCheckOnce(); }
    this._vc_23.detectChangesInNestedViews(throwOnChange);
    const currVal_63:any = import3.inlineInterpolate(1,'',this.parentView.context.username,'');
    if (import3.checkBinding(throwOnChange,this._expr_63,currVal_63)) {
      this.renderer.setText(this._text_12,currVal_63);
      this._expr_63 = currVal_63;
    }
    this._MdButton_33_3.checkHost(this,this.compView_33,this._el_33,throwOnChange);
    this._MdButton_48_3.checkHost(this,this.compView_48,this._el_48,throwOnChange);
    this.compView_4.internalDetectChanges(throwOnChange);
    this.compView_33.internalDetectChanges(throwOnChange);
    this.compView_48.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this._vc_23.destroyNestedViews();
    this.compView_4.destroy();
    this.compView_33.destroy();
    this.compView_48.destroy();
    this._RouterOutlet_23_5.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  visitProjectableNodesInternal(nodeIndex:number,ngContentIndex:number,cb:any,ctx:any):void {
    if (((nodeIndex == 33) && (ngContentIndex == 0))) { cb(this._text_34,ctx); }
    if (((nodeIndex == 48) && (ngContentIndex == 0))) { cb(this._text_49,ctx); }
  }
  handleEvent_33(eventName:string,$event:any):boolean {
    this.compView_33.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._MdButton_33_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_48(eventName:string,$event:any):boolean {
    this.compView_48.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._MdButton_48_3.handleEvent(eventName,$event) && result);
    return result;
  }
}
var renderType_DashboardComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,styles_DashboardComponent,{});
export class View_DashboardComponent0 extends import1.AppView<import0.DashboardComponent> {
  _text_0:any;
  _anchor_1:any;
  /*private*/ _vc_1:import12.ViewContainer;
  _TemplateRef_1_5:any;
  _NgIf_1_6:import22.Wrapper_NgIf;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_DashboardComponent0,renderType_DashboardComponent,import6.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._anchor_1 = this.renderer.createTemplateAnchor(parentRenderNode,(null as any));
    this._vc_1 = new import12.ViewContainer(1,(null as any),this,this._anchor_1);
    this._TemplateRef_1_5 = new import23.TemplateRef_(this,1,this._anchor_1);
    this._NgIf_1_6 = new import22.Wrapper_NgIf(this._vc_1.vcRef,this._TemplateRef_1_5);
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._text_0,
      this._anchor_1
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import23.TemplateRef) && (1 === requestNodeIndex))) { return this._TemplateRef_1_5; }
    if (((token === import24.NgIf) && (1 === requestNodeIndex))) { return this._NgIf_1_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_1_0_0:any = this.context.authenticated;
    this._NgIf_1_6.check_ngIf(currVal_1_0_0,throwOnChange,false);
    this._NgIf_1_6.ngDoCheck(this,this._anchor_1,throwOnChange);
    this._vc_1.detectChangesInNestedViews(throwOnChange);
  }
  destroyInternal():void {
    this._vc_1.destroyNestedViews();
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 1)) { return new View_DashboardComponent1(this.viewUtils,this,1,this._anchor_1,this._vc_1); }
    return (null as any);
  }
}