/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../app/components/home.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '../../../app/services/authentication.service';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/constants';
import * as import8 from '@angular/core/src/linker/component_factory';
import * as import9 from '@angular/http/src/http';
import * as import10 from '@angular/router/src/router';
import * as import11 from '@angular/material/button/button';
import * as import12 from '../../node_modules/@angular/material/button/button.ngfactory';
import * as import13 from '../../node_modules/@angular/router/src/directives/router_link.ngfactory';
import * as import14 from '../../../app/components/login-register-form.component';
import * as import15 from './login-register-form.component.ngfactory';
import * as import16 from '@angular/core/src/linker/view_container';
import * as import17 from '@angular/core/src/linker/element_ref';
import * as import18 from '@angular/router/src/router_state';
import * as import19 from '@angular/router/src/directives/router_link';
import * as import20 from '@angular/core/src/linker/query_list';
import * as import21 from '../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import22 from '../../node_modules/@angular/router/src/directives/router_outlet.ngfactory';
import * as import23 from '@angular/core/src/linker/template_ref';
import * as import24 from '@angular/router/src/router_outlet_map';
import * as import25 from '@angular/core/src/linker/component_factory_resolver';
import * as import26 from '@angular/common/src/directives/ng_if';
import * as import27 from '@angular/router/src/directives/router_outlet';
export class Wrapper_HomeComponent {
  /*private*/ _eventHandler:Function;
  context:import0.HomeComponent;
  /*private*/ _changed:boolean;
  constructor(p0:any,p1:any,p2:any) {
    this._changed = false;
    this.context = new import0.HomeComponent(p0,p1,p2);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_HomeComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_HomeComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.HomeComponent>;
  _AuthenticationService_0_3:import5.AuthenticationService;
  _HomeComponent_0_4:Wrapper_HomeComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_HomeComponent_Host0,renderType_HomeComponent_Host,import6.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'quiz-o-matic',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_HomeComponent0(this.viewUtils,this,0,this._el_0);
    this._AuthenticationService_0_3 = new import5.AuthenticationService(this.injectorGet(import9.Http,this.parentIndex));
    this._HomeComponent_0_4 = new Wrapper_HomeComponent(this._AuthenticationService_0_3,this.injectorGet(import10.Router,this.parentIndex),this.renderer);
    this.compView_0.create(this._HomeComponent_0_4.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import8.ComponentRef_<any>(0,this,this._el_0,this._HomeComponent_0_4.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import5.AuthenticationService) && (0 === requestNodeIndex))) { return this._AuthenticationService_0_3; }
    if (((token === import0.HomeComponent) && (0 === requestNodeIndex))) { return this._HomeComponent_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._HomeComponent_0_4.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const HomeComponentNgFactory:import8.ComponentFactory<import0.HomeComponent> = new import8.ComponentFactory<import0.HomeComponent>('quiz-o-matic',View_HomeComponent_Host0,import0.HomeComponent);
const styles_HomeComponent:any[] = ([] as any[]);
class View_HomeComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _text_16:any;
  _text_17:any;
  _el_18:any;
  _text_19:any;
  _el_20:any;
  compView_20:import1.AppView<import11.MdButton>;
  _MdButton_20_3:import12.Wrapper_MdButton;
  _RouterLink_20_4:import13.Wrapper_RouterLink;
  _text_21:any;
  _text_22:any;
  _text_23:any;
  _text_24:any;
  _el_25:any;
  _text_26:any;
  _el_27:any;
  _text_28:any;
  _text_29:any;
  _el_30:any;
  _text_31:any;
  _text_32:any;
  _text_33:any;
  _text_34:any;
  _text_35:any;
  _el_36:any;
  _text_37:any;
  _el_38:any;
  compView_38:import1.AppView<import14.LoginRegisterFormComponent>;
  _AuthenticationService_38_3:import5.AuthenticationService;
  _LoginRegisterFormComponent_38_4:import15.Wrapper_LoginRegisterFormComponent;
  _text_39:any;
  _text_40:any;
  _arr_47:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import16.ViewContainer) {
    super(View_HomeComponent1,renderType_HomeComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._arr_47 = import3.pureProxy2((p0:any,p1:any):any[] => {
      return [
        p0,
        p1
      ]
      ;
    });
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'class','row home'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','col-sm-8 col-xs-12'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'h3',new import3.InlineArray2(2,'class','center-xs'),(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'Welcome to Quiz-O-Matic!',(null as any));
    this._text_6 = this.renderer.createText(this._el_2,'\n          ',(null as any));
    this._el_7 = import3.createRenderElement(this.renderer,this._el_2,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_8 = this.renderer.createText(this._el_7,'Quiz-O-Matic allows you to create or take a quiz or "would you rather" which you can share with your friends and the internet. Only\n            users with an account create a quiz but anyone can take one. \n                ',(null as any));
    this._text_9 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_10 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray2(2,'class','col-xs-12 section'),(null as any));
    this._text_11 = this.renderer.createText(this._el_10,'\n            ',(null as any));
    this._el_12 = import3.createRenderElement(this.renderer,this._el_10,'div',new import3.InlineArray2(2,'class','col-sm-6 col-xs-12'),(null as any));
    this._text_13 = this.renderer.createText(this._el_12,'\n            ',(null as any));
    this._el_14 = import3.createRenderElement(this.renderer,this._el_12,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_15 = this.renderer.createText(this._el_14,'Browse through and take different quizes others have created.',(null as any));
    this._text_16 = this.renderer.createText(this._el_12,'\n            ',(null as any));
    this._text_17 = this.renderer.createText(this._el_10,'\n                ',(null as any));
    this._el_18 = import3.createRenderElement(this.renderer,this._el_10,'div',new import3.InlineArray2(2,'class','col-sm-6 col-xs-12'),(null as any));
    this._text_19 = this.renderer.createText(this._el_18,'\n                    ',(null as any));
    this._el_20 = import3.createRenderElement(this.renderer,this._el_18,'button',new import3.InlineArray8(8,'button','','class','primaryButton center','color','primary','md-raised-button',''),(null as any));
    this.compView_20 = new import12.View_MdButton0(this.viewUtils,this,20,this._el_20);
    this._MdButton_20_3 = new import12.Wrapper_MdButton(new import17.ElementRef(this._el_20),this.renderer);
    this._RouterLink_20_4 = new import13.Wrapper_RouterLink(this.parentView.injectorGet(import10.Router,this.parentIndex),this.parentView.injectorGet(import18.ActivatedRoute,this.parentIndex));
    this._text_21 = this.renderer.createText((null as any),'Take a Quiz',(null as any));
    this.compView_20.create(this._MdButton_20_3.context);
    this._text_22 = this.renderer.createText(this._el_18,'        \n            ',(null as any));
    this._text_23 = this.renderer.createText(this._el_10,'\n        ',(null as any));
    this._text_24 = this.renderer.createText(this._el_2,'\n         ',(null as any));
    this._el_25 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray2(2,'class','col-xs-12 section'),(null as any));
    this._text_26 = this.renderer.createText(this._el_25,'  \n            ',(null as any));
    this._el_27 = import3.createRenderElement(this.renderer,this._el_25,'div',new import3.InlineArray2(2,'class','col-sm-6 col-xs-12'),(null as any));
    this._text_28 = this.renderer.createText(this._el_27,'\n            ',(null as any));
    this._text_29 = this.renderer.createText(this._el_25,'\n            ',(null as any));
    this._el_30 = import3.createRenderElement(this.renderer,this._el_25,'div',new import3.InlineArray2(2,'class','col-sm-6 col-xs-12'),(null as any));
    this._text_31 = this.renderer.createText(this._el_30,'\n                ',(null as any));
    this._text_32 = this.renderer.createText(this._el_30,'\n            ',(null as any));
    this._text_33 = this.renderer.createText(this._el_25,'          \n        ',(null as any));
    this._text_34 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_35 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_36 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','col-sm-4 col-xs-12'),(null as any));
    this._text_37 = this.renderer.createText(this._el_36,'\n        ',(null as any));
    this._el_38 = import3.createRenderElement(this.renderer,this._el_36,'login-register-form',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_38 = new import15.View_LoginRegisterFormComponent0(this.viewUtils,this,38,this._el_38);
    this._AuthenticationService_38_3 = new import5.AuthenticationService(this.parentView.injectorGet(import9.Http,this.parentIndex));
    this._LoginRegisterFormComponent_38_4 = new import15.Wrapper_LoginRegisterFormComponent(this._AuthenticationService_38_3,this.parentView.injectorGet(import10.Router,this.parentIndex),this.parentView.injectorGet(import9.Http,this.parentIndex));
    this.compView_38.create(this._LoginRegisterFormComponent_38_4.context);
    this._text_39 = this.renderer.createText(this._el_36,'\n    ',(null as any));
    this._text_40 = this.renderer.createText(this._el_0,'\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_20,new import3.InlineArray8(8,'mousedown',(null as any),'focus',(null as any),'blur',(null as any),'click',(null as any)),this.eventHandler(this.handleEvent_20));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._text_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._text_32,
      this._text_33,
      this._text_34,
      this._text_35,
      this._el_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._text_40
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import11.MdButton) && ((20 <= requestNodeIndex) && (requestNodeIndex <= 21)))) { return this._MdButton_20_3.context; }
    if (((token === import19.RouterLink) && ((20 <= requestNodeIndex) && (requestNodeIndex <= 21)))) { return this._RouterLink_20_4.context; }
    if (((token === import5.AuthenticationService) && (38 === requestNodeIndex))) { return this._AuthenticationService_38_3; }
    if (((token === import14.LoginRegisterFormComponent) && (38 === requestNodeIndex))) { return this._LoginRegisterFormComponent_38_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_20_0_0:any = 'primary';
    this._MdButton_20_3.check_color(currVal_20_0_0,throwOnChange,false);
    if (this._MdButton_20_3.ngDoCheck(this,this._el_20,throwOnChange)) { this.compView_20.markAsCheckOnce(); }
    const currVal_20_1_0:any = this._arr_47('/take-quiz','list');
    this._RouterLink_20_4.check_routerLink(currVal_20_1_0,throwOnChange,false);
    this._RouterLink_20_4.ngDoCheck(this,this._el_20,throwOnChange);
    this._LoginRegisterFormComponent_38_4.ngDoCheck(this,this._el_38,throwOnChange);
    this._MdButton_20_3.checkHost(this,this.compView_20,this._el_20,throwOnChange);
    this.compView_20.internalDetectChanges(throwOnChange);
    this.compView_38.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_20.destroy();
    this.compView_38.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  visitProjectableNodesInternal(nodeIndex:number,ngContentIndex:number,cb:any,ctx:any):void {
    if (((nodeIndex == 20) && (ngContentIndex == 0))) { cb(this._text_21,ctx); }
  }
  handleEvent_20(eventName:string,$event:any):boolean {
    this.compView_20.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._MdButton_20_3.handleEvent(eventName,$event) && result);
    result = (this._RouterLink_20_4.handleEvent(eventName,$event) && result);
    return result;
  }
}
var renderType_HomeComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,styles_HomeComponent,{});
export class View_HomeComponent0 extends import1.AppView<import0.HomeComponent> {
  _viewQuery_createLink_0:import20.QueryList<any>;
  _text_0:any;
  _anchor_1:any;
  /*private*/ _vc_1:import16.ViewContainer;
  _TemplateRef_1_5:any;
  _NgIf_1_6:import21.Wrapper_NgIf;
  _text_2:any;
  _el_3:any;
  /*private*/ _vc_3:import16.ViewContainer;
  _RouterOutlet_3_5:import22.Wrapper_RouterOutlet;
  _text_4:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_HomeComponent0,renderType_HomeComponent,import6.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._viewQuery_createLink_0 = new import20.QueryList<any>();
    this._text_0 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._anchor_1 = this.renderer.createTemplateAnchor(parentRenderNode,(null as any));
    this._vc_1 = new import16.ViewContainer(1,(null as any),this,this._anchor_1);
    this._TemplateRef_1_5 = new import23.TemplateRef_(this,1,this._anchor_1);
    this._NgIf_1_6 = new import21.Wrapper_NgIf(this._vc_1.vcRef,this._TemplateRef_1_5);
    this._text_2 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_3 = import3.createRenderElement(this.renderer,parentRenderNode,'router-outlet',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._vc_3 = new import16.ViewContainer(3,(null as any),this,this._el_3);
    this._RouterOutlet_3_5 = new import22.Wrapper_RouterOutlet(this.parentView.injectorGet(import24.RouterOutletMap,this.parentIndex),this._vc_3.vcRef,this.parentView.injectorGet(import25.ComponentFactoryResolver,this.parentIndex),(null as any));
    this._text_4 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._viewQuery_createLink_0.reset(([] as any[]));
    this.context.clickElRef = this._viewQuery_createLink_0.first;
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._text_0,
      this._anchor_1,
      this._text_2,
      this._el_3,
      this._text_4
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import23.TemplateRef) && (1 === requestNodeIndex))) { return this._TemplateRef_1_5; }
    if (((token === import26.NgIf) && (1 === requestNodeIndex))) { return this._NgIf_1_6.context; }
    if (((token === import27.RouterOutlet) && (3 === requestNodeIndex))) { return this._RouterOutlet_3_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_1_0_0:any = this.context.loaded;
    this._NgIf_1_6.check_ngIf(currVal_1_0_0,throwOnChange,false);
    this._NgIf_1_6.ngDoCheck(this,this._anchor_1,throwOnChange);
    this._RouterOutlet_3_5.ngDoCheck(this,this._el_3,throwOnChange);
    this._vc_1.detectChangesInNestedViews(throwOnChange);
    this._vc_3.detectChangesInNestedViews(throwOnChange);
  }
  destroyInternal():void {
    this._vc_1.destroyNestedViews();
    this._vc_3.destroyNestedViews();
    this._RouterOutlet_3_5.ngOnDestroy();
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 1)) { return new View_HomeComponent1(this.viewUtils,this,1,this._anchor_1,this._vc_1); }
    return (null as any);
  }
}