/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../app/components/login-register-form.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '../../../app/services/authentication.service';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/constants';
import * as import8 from '@angular/core/src/linker/component_factory';
import * as import9 from '@angular/http/src/http';
import * as import10 from '@angular/router/src/router';
import * as import11 from '../../node_modules/@angular/forms/src/directives/ng_form.ngfactory';
import * as import12 from '../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import13 from '../../node_modules/@angular/forms/src/directives/default_value_accessor.ngfactory';
import * as import14 from '../../node_modules/@angular/forms/src/directives/validators.ngfactory';
import * as import15 from '../../node_modules/@angular/forms/src/directives/ng_model.ngfactory';
import * as import16 from '@angular/material/button/button';
import * as import17 from '../../node_modules/@angular/material/button/button.ngfactory';
import * as import18 from '@angular/core/src/linker/view_container';
import * as import19 from '@angular/core/src/linker/element_ref';
import * as import20 from '@angular/forms/src/directives/default_value_accessor';
import * as import21 from '@angular/forms/src/directives/validators';
import * as import22 from '@angular/forms/src/validators';
import * as import23 from '@angular/forms/src/directives/control_value_accessor';
import * as import24 from '@angular/forms/src/directives/ng_model';
import * as import25 from '@angular/forms/src/directives/ng_control';
import * as import26 from '@angular/forms/src/directives/ng_control_status';
import * as import27 from '@angular/forms/src/directives/ng_form';
import * as import28 from '@angular/forms/src/directives/control_container';
import * as import29 from '@angular/core/src/change_detection/change_detection_util';
import * as import30 from '../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import31 from '@angular/core/src/linker/template_ref';
import * as import32 from '@angular/common/src/directives/ng_if';
export class Wrapper_LoginRegisterFormComponent {
  /*private*/ _eventHandler:Function;
  context:import0.LoginRegisterFormComponent;
  /*private*/ _changed:boolean;
  constructor(p0:any,p1:any,p2:any) {
    this._changed = false;
    this.context = new import0.LoginRegisterFormComponent(p0,p1,p2);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_LoginRegisterFormComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_LoginRegisterFormComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.LoginRegisterFormComponent>;
  _AuthenticationService_0_3:import5.AuthenticationService;
  _LoginRegisterFormComponent_0_4:Wrapper_LoginRegisterFormComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_LoginRegisterFormComponent_Host0,renderType_LoginRegisterFormComponent_Host,import6.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'login-register-form',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_LoginRegisterFormComponent0(this.viewUtils,this,0,this._el_0);
    this._AuthenticationService_0_3 = new import5.AuthenticationService(this.injectorGet(import9.Http,this.parentIndex));
    this._LoginRegisterFormComponent_0_4 = new Wrapper_LoginRegisterFormComponent(this._AuthenticationService_0_3,this.injectorGet(import10.Router,this.parentIndex),this.injectorGet(import9.Http,this.parentIndex));
    this.compView_0.create(this._LoginRegisterFormComponent_0_4.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import8.ComponentRef_<any>(0,this,this._el_0,this._LoginRegisterFormComponent_0_4.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import5.AuthenticationService) && (0 === requestNodeIndex))) { return this._AuthenticationService_0_3; }
    if (((token === import0.LoginRegisterFormComponent) && (0 === requestNodeIndex))) { return this._LoginRegisterFormComponent_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._LoginRegisterFormComponent_0_4.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const LoginRegisterFormComponentNgFactory:import8.ComponentFactory<import0.LoginRegisterFormComponent> = new import8.ComponentFactory<import0.LoginRegisterFormComponent>('login-register-form',View_LoginRegisterFormComponent_Host0,import0.LoginRegisterFormComponent);
const styles_LoginRegisterFormComponent:any[] = ([] as any[]);
class View_LoginRegisterFormComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _text_7:any;
  _el_8:any;
  _NgForm_8_3:import11.Wrapper_NgForm;
  _ControlContainer_8_4:any;
  _NgControlStatusGroup_8_5:import12.Wrapper_NgControlStatusGroup;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _text_14:any;
  _el_15:any;
  _DefaultValueAccessor_15_3:import13.Wrapper_DefaultValueAccessor;
  _RequiredValidator_15_4:import14.Wrapper_RequiredValidator;
  _NG_VALIDATORS_15_5:any[];
  _NG_VALUE_ACCESSOR_15_6:any[];
  _NgModel_15_7:import15.Wrapper_NgModel;
  _NgControl_15_8:any;
  _NgControlStatus_15_9:import12.Wrapper_NgControlStatus;
  _text_16:any;
  _text_17:any;
  _el_18:any;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _text_22:any;
  _el_23:any;
  _DefaultValueAccessor_23_3:import13.Wrapper_DefaultValueAccessor;
  _RequiredValidator_23_4:import14.Wrapper_RequiredValidator;
  _NG_VALIDATORS_23_5:any[];
  _NG_VALUE_ACCESSOR_23_6:any[];
  _NgModel_23_7:import15.Wrapper_NgModel;
  _NgControl_23_8:any;
  _NgControlStatus_23_9:import12.Wrapper_NgControlStatus;
  _text_24:any;
  _text_25:any;
  _el_26:any;
  compView_26:import1.AppView<import16.MdButton>;
  _MdButton_26_3:import17.Wrapper_MdButton;
  _text_27:any;
  _text_28:any;
  _text_29:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import18.ViewContainer) {
    super(View_LoginRegisterFormComponent1,renderType_LoginRegisterFormComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'h3',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'Login',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_5 = import3.createRenderElement(this.renderer,this._el_0,'a',new import3.InlineArray2(2,'class','right create-link'),(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'Create an account',(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_8 = import3.createRenderElement(this.renderer,this._el_0,'form',new import3.InlineArray2(2,'name','login-form'),(null as any));
    this._NgForm_8_3 = new import11.Wrapper_NgForm((null as any),(null as any));
    this._ControlContainer_8_4 = this._NgForm_8_3.context;
    this._NgControlStatusGroup_8_5 = new import12.Wrapper_NgControlStatusGroup(this._ControlContainer_8_4);
    this._text_9 = this.renderer.createText(this._el_8,'\n        ',(null as any));
    this._el_10 = import3.createRenderElement(this.renderer,this._el_8,'div',new import3.InlineArray2(2,'class','form-group'),(null as any));
    this._text_11 = this.renderer.createText(this._el_10,'\n            ',(null as any));
    this._el_12 = import3.createRenderElement(this.renderer,this._el_10,'label',new import3.InlineArray2(2,'for','username'),(null as any));
    this._text_13 = this.renderer.createText(this._el_12,'Username:',(null as any));
    this._text_14 = this.renderer.createText(this._el_10,'\n            ',(null as any));
    this._el_15 = import3.createRenderElement(this.renderer,this._el_10,'input',new import3.InlineArray16(12,'class','form-control','id','username','name','username','placeholder','Username','required','','type','text'),(null as any));
    this._DefaultValueAccessor_15_3 = new import13.Wrapper_DefaultValueAccessor(this.renderer,new import19.ElementRef(this._el_15));
    this._RequiredValidator_15_4 = new import14.Wrapper_RequiredValidator();
    this._NG_VALIDATORS_15_5 = [this._RequiredValidator_15_4.context];
    this._NG_VALUE_ACCESSOR_15_6 = [this._DefaultValueAccessor_15_3.context];
    this._NgModel_15_7 = new import15.Wrapper_NgModel(this._ControlContainer_8_4,this._NG_VALIDATORS_15_5,(null as any),this._NG_VALUE_ACCESSOR_15_6);
    this._NgControl_15_8 = this._NgModel_15_7.context;
    this._NgControlStatus_15_9 = new import12.Wrapper_NgControlStatus(this._NgControl_15_8);
    this._text_16 = this.renderer.createText(this._el_10,'\n        ',(null as any));
    this._text_17 = this.renderer.createText(this._el_8,'            \n        ',(null as any));
    this._el_18 = import3.createRenderElement(this.renderer,this._el_8,'div',new import3.InlineArray2(2,'class','form-group'),(null as any));
    this._text_19 = this.renderer.createText(this._el_18,'\n            ',(null as any));
    this._el_20 = import3.createRenderElement(this.renderer,this._el_18,'label',new import3.InlineArray2(2,'for','password'),(null as any));
    this._text_21 = this.renderer.createText(this._el_20,'Password:',(null as any));
    this._text_22 = this.renderer.createText(this._el_18,'\n            ',(null as any));
    this._el_23 = import3.createRenderElement(this.renderer,this._el_18,'input',new import3.InlineArray16(12,'class','form-control','id','password','name','password','placeholder','········','required','','type','password'),(null as any));
    this._DefaultValueAccessor_23_3 = new import13.Wrapper_DefaultValueAccessor(this.renderer,new import19.ElementRef(this._el_23));
    this._RequiredValidator_23_4 = new import14.Wrapper_RequiredValidator();
    this._NG_VALIDATORS_23_5 = [this._RequiredValidator_23_4.context];
    this._NG_VALUE_ACCESSOR_23_6 = [this._DefaultValueAccessor_23_3.context];
    this._NgModel_23_7 = new import15.Wrapper_NgModel(this._ControlContainer_8_4,this._NG_VALIDATORS_23_5,(null as any),this._NG_VALUE_ACCESSOR_23_6);
    this._NgControl_23_8 = this._NgModel_23_7.context;
    this._NgControlStatus_23_9 = new import12.Wrapper_NgControlStatus(this._NgControl_23_8);
    this._text_24 = this.renderer.createText(this._el_18,'\n        ',(null as any));
    this._text_25 = this.renderer.createText(this._el_8,'     \n        ',(null as any));
    this._el_26 = import3.createRenderElement(this.renderer,this._el_8,'button',new import3.InlineArray8(8,'class','loginButton center','id','submitPasword','md-raised-button','','type','submit'),(null as any));
    this.compView_26 = new import17.View_MdButton0(this.viewUtils,this,26,this._el_26);
    this._MdButton_26_3 = new import17.Wrapper_MdButton(new import19.ElementRef(this._el_26),this.renderer);
    this._text_27 = this.renderer.createText((null as any),'\n            Submit\n        ',(null as any));
    this.compView_26.create(this._MdButton_26_3.context);
    this._text_28 = this.renderer.createText(this._el_8,'       \n    ',(null as any));
    this._text_29 = this.renderer.createText(this._el_0,'\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_5,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_5));
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_8,new import3.InlineArray8(6,'ngSubmit',(null as any),'submit',(null as any),'reset',(null as any)),this.eventHandler(this.handleEvent_8));
    this._NgForm_8_3.subscribe(this,this.eventHandler(this.handleEvent_8),true);
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_15,new import3.InlineArray8(6,'ngModelChange',(null as any),'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_15));
    this._NgModel_15_7.subscribe(this,this.eventHandler(this.handleEvent_15),true);
    var disposable_3:Function = import3.subscribeToRenderElement(this,this._el_23,new import3.InlineArray8(6,'ngModelChange',(null as any),'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_23));
    this._NgModel_23_7.subscribe(this,this.eventHandler(this.handleEvent_23),true);
    var disposable_4:Function = import3.subscribeToRenderElement(this,this._el_26,new import3.InlineArray8(6,'mousedown',(null as any),'focus',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_26));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._text_28,
      this._text_29
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import20.DefaultValueAccessor) && (15 === requestNodeIndex))) { return this._DefaultValueAccessor_15_3.context; }
    if (((token === import21.RequiredValidator) && (15 === requestNodeIndex))) { return this._RequiredValidator_15_4.context; }
    if (((token === import22.NG_VALIDATORS) && (15 === requestNodeIndex))) { return this._NG_VALIDATORS_15_5; }
    if (((token === import23.NG_VALUE_ACCESSOR) && (15 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_15_6; }
    if (((token === import24.NgModel) && (15 === requestNodeIndex))) { return this._NgModel_15_7.context; }
    if (((token === import25.NgControl) && (15 === requestNodeIndex))) { return this._NgControl_15_8; }
    if (((token === import26.NgControlStatus) && (15 === requestNodeIndex))) { return this._NgControlStatus_15_9.context; }
    if (((token === import20.DefaultValueAccessor) && (23 === requestNodeIndex))) { return this._DefaultValueAccessor_23_3.context; }
    if (((token === import21.RequiredValidator) && (23 === requestNodeIndex))) { return this._RequiredValidator_23_4.context; }
    if (((token === import22.NG_VALIDATORS) && (23 === requestNodeIndex))) { return this._NG_VALIDATORS_23_5; }
    if (((token === import23.NG_VALUE_ACCESSOR) && (23 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_23_6; }
    if (((token === import24.NgModel) && (23 === requestNodeIndex))) { return this._NgModel_23_7.context; }
    if (((token === import25.NgControl) && (23 === requestNodeIndex))) { return this._NgControl_23_8; }
    if (((token === import26.NgControlStatus) && (23 === requestNodeIndex))) { return this._NgControlStatus_23_9.context; }
    if (((token === import16.MdButton) && ((26 <= requestNodeIndex) && (requestNodeIndex <= 27)))) { return this._MdButton_26_3.context; }
    if (((token === import27.NgForm) && ((8 <= requestNodeIndex) && (requestNodeIndex <= 28)))) { return this._NgForm_8_3.context; }
    if (((token === import28.ControlContainer) && ((8 <= requestNodeIndex) && (requestNodeIndex <= 28)))) { return this._ControlContainer_8_4; }
    if (((token === import26.NgControlStatusGroup) && ((8 <= requestNodeIndex) && (requestNodeIndex <= 28)))) { return this._NgControlStatusGroup_8_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._NgForm_8_3.ngDoCheck(this,this._el_8,throwOnChange);
    this._NgControlStatusGroup_8_5.ngDoCheck(this,this._el_8,throwOnChange);
    this._DefaultValueAccessor_15_3.ngDoCheck(this,this._el_15,throwOnChange);
    const currVal_15_1_0:any = '';
    this._RequiredValidator_15_4.check_required(currVal_15_1_0,throwOnChange,false);
    this._RequiredValidator_15_4.ngDoCheck(this,this._el_15,throwOnChange);
    const currVal_15_2_0:any = 'username';
    this._NgModel_15_7.check_name(currVal_15_2_0,throwOnChange,false);
    const currVal_15_2_1:any = this.parentView.context.model.username;
    this._NgModel_15_7.check_model(currVal_15_2_1,throwOnChange,false);
    this._NgModel_15_7.ngDoCheck(this,this._el_15,throwOnChange);
    this._NgControlStatus_15_9.ngDoCheck(this,this._el_15,throwOnChange);
    this._DefaultValueAccessor_23_3.ngDoCheck(this,this._el_23,throwOnChange);
    const currVal_23_1_0:any = '';
    this._RequiredValidator_23_4.check_required(currVal_23_1_0,throwOnChange,false);
    this._RequiredValidator_23_4.ngDoCheck(this,this._el_23,throwOnChange);
    const currVal_23_2_0:any = 'password';
    this._NgModel_23_7.check_name(currVal_23_2_0,throwOnChange,false);
    const currVal_23_2_1:any = this.parentView.context.model.password;
    this._NgModel_23_7.check_model(currVal_23_2_1,throwOnChange,false);
    this._NgModel_23_7.ngDoCheck(this,this._el_23,throwOnChange);
    this._NgControlStatus_23_9.ngDoCheck(this,this._el_23,throwOnChange);
    const currVal_26_0_0:boolean = !this._NgForm_8_3.context.form.valid;
    this._MdButton_26_3.check_disabled(currVal_26_0_0,throwOnChange,false);
    if (this._MdButton_26_3.ngDoCheck(this,this._el_26,throwOnChange)) { this.compView_26.markAsCheckOnce(); }
    this._NgControlStatusGroup_8_5.checkHost(this,this,this._el_8,throwOnChange);
    this._RequiredValidator_15_4.checkHost(this,this,this._el_15,throwOnChange);
    this._NgControlStatus_15_9.checkHost(this,this,this._el_15,throwOnChange);
    this._RequiredValidator_23_4.checkHost(this,this,this._el_23,throwOnChange);
    this._NgControlStatus_23_9.checkHost(this,this,this._el_23,throwOnChange);
    this._MdButton_26_3.checkHost(this,this.compView_26,this._el_26,throwOnChange);
    this.compView_26.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_26.destroy();
    this._NgModel_15_7.ngOnDestroy();
    this._NgModel_23_7.ngOnDestroy();
    this._NgForm_8_3.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  visitProjectableNodesInternal(nodeIndex:number,ngContentIndex:number,cb:any,ctx:any):void {
    if (((nodeIndex == 26) && (ngContentIndex == 0))) { cb(this._text_27,ctx); }
  }
  handleEvent_5(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.context.toggleRegister()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_8(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._NgForm_8_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngSubmit')) {
      const pd_sub_0:any = ((<any>this.parentView.context.loginUser($event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_15(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_15_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.parentView.context.model.username = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_23(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_23_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.parentView.context.model.password = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_26(eventName:string,$event:any):boolean {
    this.compView_26.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._MdButton_26_3.handleEvent(eventName,$event) && result);
    return result;
  }
}
class View_LoginRegisterFormComponent3 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import18.ViewContainer) {
    super(View_LoginRegisterFormComponent3,renderType_LoginRegisterFormComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_2 = import29.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'span',new import3.InlineArray2(2,'style','font-weight: normal;'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2:any = import3.inlineInterpolate(1,'\n                ',this.parentView.parentView.context.passwordReqText,'\n                ');
    if (import3.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_1,currVal_2);
      this._expr_2 = currVal_2;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_LoginRegisterFormComponent2 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _text_7:any;
  _el_8:any;
  _NgForm_8_3:import11.Wrapper_NgForm;
  _ControlContainer_8_4:any;
  _NgControlStatusGroup_8_5:import12.Wrapper_NgControlStatusGroup;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _text_14:any;
  _el_15:any;
  _DefaultValueAccessor_15_3:import13.Wrapper_DefaultValueAccessor;
  _RequiredValidator_15_4:import14.Wrapper_RequiredValidator;
  _NG_VALIDATORS_15_5:any[];
  _NG_VALUE_ACCESSOR_15_6:any[];
  _NgModel_15_7:import15.Wrapper_NgModel;
  _NgControl_15_8:any;
  _NgControlStatus_15_9:import12.Wrapper_NgControlStatus;
  _text_16:any;
  _text_17:any;
  _el_18:any;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _text_22:any;
  _el_23:any;
  _text_24:any;
  _text_25:any;
  _anchor_26:any;
  /*private*/ _vc_26:import18.ViewContainer;
  _TemplateRef_26_5:any;
  _NgIf_26_6:import30.Wrapper_NgIf;
  _text_27:any;
  _el_28:any;
  _DefaultValueAccessor_28_3:import13.Wrapper_DefaultValueAccessor;
  _RequiredValidator_28_4:import14.Wrapper_RequiredValidator;
  _NG_VALIDATORS_28_5:any[];
  _NG_VALUE_ACCESSOR_28_6:any[];
  _NgModel_28_7:import15.Wrapper_NgModel;
  _NgControl_28_8:any;
  _NgControlStatus_28_9:import12.Wrapper_NgControlStatus;
  _text_29:any;
  _text_30:any;
  _el_31:any;
  _text_32:any;
  _el_33:any;
  _text_34:any;
  _text_35:any;
  _el_36:any;
  _DefaultValueAccessor_36_3:import13.Wrapper_DefaultValueAccessor;
  _RequiredValidator_36_4:import14.Wrapper_RequiredValidator;
  _NG_VALIDATORS_36_5:any[];
  _NG_VALUE_ACCESSOR_36_6:any[];
  _NgModel_36_7:import15.Wrapper_NgModel;
  _NgControl_36_8:any;
  _NgControlStatus_36_9:import12.Wrapper_NgControlStatus;
  _text_37:any;
  _text_38:any;
  _el_39:any;
  compView_39:import1.AppView<import16.MdButton>;
  _MdButton_39_3:import17.Wrapper_MdButton;
  _text_40:any;
  _text_41:any;
  _text_42:any;
  /*private*/ _expr_72:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import18.ViewContainer) {
    super(View_LoginRegisterFormComponent2,renderType_LoginRegisterFormComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_72 = import29.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'h3',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'Register',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_5 = import3.createRenderElement(this.renderer,this._el_0,'a',new import3.InlineArray2(2,'class','right create-link'),(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'Login',(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_8 = import3.createRenderElement(this.renderer,this._el_0,'form',new import3.InlineArray2(2,'name','register-form'),(null as any));
    this._NgForm_8_3 = new import11.Wrapper_NgForm((null as any),(null as any));
    this._ControlContainer_8_4 = this._NgForm_8_3.context;
    this._NgControlStatusGroup_8_5 = new import12.Wrapper_NgControlStatusGroup(this._ControlContainer_8_4);
    this._text_9 = this.renderer.createText(this._el_8,'\n        ',(null as any));
    this._el_10 = import3.createRenderElement(this.renderer,this._el_8,'div',new import3.InlineArray2(2,'class','form-group'),(null as any));
    this._text_11 = this.renderer.createText(this._el_10,'\n            ',(null as any));
    this._el_12 = import3.createRenderElement(this.renderer,this._el_10,'label',new import3.InlineArray2(2,'for','reg-email'),(null as any));
    this._text_13 = this.renderer.createText(this._el_12,'Email:',(null as any));
    this._text_14 = this.renderer.createText(this._el_10,'\n            ',(null as any));
    this._el_15 = import3.createRenderElement(this.renderer,this._el_10,'input',new import3.InlineArray16(12,'class','form-control','id','reg-email','name','regEmail','placeholder','handle@site.com','required','','type','email'),(null as any));
    this._DefaultValueAccessor_15_3 = new import13.Wrapper_DefaultValueAccessor(this.renderer,new import19.ElementRef(this._el_15));
    this._RequiredValidator_15_4 = new import14.Wrapper_RequiredValidator();
    this._NG_VALIDATORS_15_5 = [this._RequiredValidator_15_4.context];
    this._NG_VALUE_ACCESSOR_15_6 = [this._DefaultValueAccessor_15_3.context];
    this._NgModel_15_7 = new import15.Wrapper_NgModel(this._ControlContainer_8_4,this._NG_VALIDATORS_15_5,(null as any),this._NG_VALUE_ACCESSOR_15_6);
    this._NgControl_15_8 = this._NgModel_15_7.context;
    this._NgControlStatus_15_9 = new import12.Wrapper_NgControlStatus(this._NgControl_15_8);
    this._text_16 = this.renderer.createText(this._el_10,'\n        ',(null as any));
    this._text_17 = this.renderer.createText(this._el_8,'\n        ',(null as any));
    this._el_18 = import3.createRenderElement(this.renderer,this._el_8,'div',new import3.InlineArray2(2,'class','form-group'),(null as any));
    this._text_19 = this.renderer.createText(this._el_18,'\n            ',(null as any));
    this._el_20 = import3.createRenderElement(this.renderer,this._el_18,'label',new import3.InlineArray2(2,'for','reg-password'),(null as any));
    this._text_21 = this.renderer.createText(this._el_20,'Password: \n            ',(null as any));
    this._text_22 = this.renderer.createText(this._el_18,'\n             ',(null as any));
    this._el_23 = import3.createRenderElement(this.renderer,this._el_18,'a',new import3.InlineArray4(4,'class','right','style','cursor:pointer'),(null as any));
    this._text_24 = this.renderer.createText(this._el_23,'\n                ?',(null as any));
    this._text_25 = this.renderer.createText(this._el_18,'\n            ',(null as any));
    this._anchor_26 = this.renderer.createTemplateAnchor(this._el_18,(null as any));
    this._vc_26 = new import18.ViewContainer(26,18,this,this._anchor_26);
    this._TemplateRef_26_5 = new import31.TemplateRef_(this,26,this._anchor_26);
    this._NgIf_26_6 = new import30.Wrapper_NgIf(this._vc_26.vcRef,this._TemplateRef_26_5);
    this._text_27 = this.renderer.createText(this._el_18,'\n            ',(null as any));
    this._el_28 = import3.createRenderElement(this.renderer,this._el_18,'input',new import3.InlineArray16(12,'class','form-control','id','reg-password','name','regPassword','placeholder','········','required','','type','password'),(null as any));
    this._DefaultValueAccessor_28_3 = new import13.Wrapper_DefaultValueAccessor(this.renderer,new import19.ElementRef(this._el_28));
    this._RequiredValidator_28_4 = new import14.Wrapper_RequiredValidator();
    this._NG_VALIDATORS_28_5 = [this._RequiredValidator_28_4.context];
    this._NG_VALUE_ACCESSOR_28_6 = [this._DefaultValueAccessor_28_3.context];
    this._NgModel_28_7 = new import15.Wrapper_NgModel(this._ControlContainer_8_4,this._NG_VALIDATORS_28_5,(null as any),this._NG_VALUE_ACCESSOR_28_6);
    this._NgControl_28_8 = this._NgModel_28_7.context;
    this._NgControlStatus_28_9 = new import12.Wrapper_NgControlStatus(this._NgControl_28_8);
    this._text_29 = this.renderer.createText(this._el_18,'\n        ',(null as any));
    this._text_30 = this.renderer.createText(this._el_8,'\n        ',(null as any));
    this._el_31 = import3.createRenderElement(this.renderer,this._el_8,'div',new import3.InlineArray2(2,'class','form-group'),(null as any));
    this._text_32 = this.renderer.createText(this._el_31,'\n            ',(null as any));
    this._el_33 = import3.createRenderElement(this.renderer,this._el_31,'label',new import3.InlineArray2(2,'for','reg-confirm-password'),(null as any));
    this._text_34 = this.renderer.createText(this._el_33,'Confirm Password:',(null as any));
    this._text_35 = this.renderer.createText(this._el_31,'\n            ',(null as any));
    this._el_36 = import3.createRenderElement(this.renderer,this._el_31,'input',new import3.InlineArray16(12,'class','form-control','id','reg-confirm-password','name','regConfirmPassword','placeholder','········','required','','type','password'),(null as any));
    this._DefaultValueAccessor_36_3 = new import13.Wrapper_DefaultValueAccessor(this.renderer,new import19.ElementRef(this._el_36));
    this._RequiredValidator_36_4 = new import14.Wrapper_RequiredValidator();
    this._NG_VALIDATORS_36_5 = [this._RequiredValidator_36_4.context];
    this._NG_VALUE_ACCESSOR_36_6 = [this._DefaultValueAccessor_36_3.context];
    this._NgModel_36_7 = new import15.Wrapper_NgModel(this._ControlContainer_8_4,this._NG_VALIDATORS_36_5,(null as any),this._NG_VALUE_ACCESSOR_36_6);
    this._NgControl_36_8 = this._NgModel_36_7.context;
    this._NgControlStatus_36_9 = new import12.Wrapper_NgControlStatus(this._NgControl_36_8);
    this._text_37 = this.renderer.createText(this._el_31,'\n        ',(null as any));
    this._text_38 = this.renderer.createText(this._el_8,'\n        ',(null as any));
    this._el_39 = import3.createRenderElement(this.renderer,this._el_8,'button',new import3.InlineArray8(8,'class','loginButton center','id','submitRegister','md-raised-button','','type','submit'),(null as any));
    this.compView_39 = new import17.View_MdButton0(this.viewUtils,this,39,this._el_39);
    this._MdButton_39_3 = new import17.Wrapper_MdButton(new import19.ElementRef(this._el_39),this.renderer);
    this._text_40 = this.renderer.createText((null as any),'\n            Submit\n        ',(null as any));
    this.compView_39.create(this._MdButton_39_3.context);
    this._text_41 = this.renderer.createText(this._el_8,'       \n    ',(null as any));
    this._text_42 = this.renderer.createText(this._el_0,'\n\n\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_5,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_5));
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_8,new import3.InlineArray8(6,'ngSubmit',(null as any),'submit',(null as any),'reset',(null as any)),this.eventHandler(this.handleEvent_8));
    this._NgForm_8_3.subscribe(this,this.eventHandler(this.handleEvent_8),true);
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_15,new import3.InlineArray8(6,'ngModelChange',(null as any),'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_15));
    this._NgModel_15_7.subscribe(this,this.eventHandler(this.handleEvent_15),true);
    var disposable_3:Function = import3.subscribeToRenderElement(this,this._el_23,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_23));
    var disposable_4:Function = import3.subscribeToRenderElement(this,this._el_28,new import3.InlineArray8(6,'ngModelChange',(null as any),'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_28));
    this._NgModel_28_7.subscribe(this,this.eventHandler(this.handleEvent_28),true);
    var disposable_5:Function = import3.subscribeToRenderElement(this,this._el_36,new import3.InlineArray8(6,'ngModelChange',(null as any),'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_36));
    this._NgModel_36_7.subscribe(this,this.eventHandler(this.handleEvent_36),true);
    var disposable_6:Function = import3.subscribeToRenderElement(this,this._el_39,new import3.InlineArray8(6,'mousedown',(null as any),'focus',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_39));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._text_25,
      this._anchor_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._text_35,
      this._el_36,
      this._text_37,
      this._text_38,
      this._el_39,
      this._text_40,
      this._text_41,
      this._text_42
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import20.DefaultValueAccessor) && (15 === requestNodeIndex))) { return this._DefaultValueAccessor_15_3.context; }
    if (((token === import21.RequiredValidator) && (15 === requestNodeIndex))) { return this._RequiredValidator_15_4.context; }
    if (((token === import22.NG_VALIDATORS) && (15 === requestNodeIndex))) { return this._NG_VALIDATORS_15_5; }
    if (((token === import23.NG_VALUE_ACCESSOR) && (15 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_15_6; }
    if (((token === import24.NgModel) && (15 === requestNodeIndex))) { return this._NgModel_15_7.context; }
    if (((token === import25.NgControl) && (15 === requestNodeIndex))) { return this._NgControl_15_8; }
    if (((token === import26.NgControlStatus) && (15 === requestNodeIndex))) { return this._NgControlStatus_15_9.context; }
    if (((token === import31.TemplateRef) && (26 === requestNodeIndex))) { return this._TemplateRef_26_5; }
    if (((token === import32.NgIf) && (26 === requestNodeIndex))) { return this._NgIf_26_6.context; }
    if (((token === import20.DefaultValueAccessor) && (28 === requestNodeIndex))) { return this._DefaultValueAccessor_28_3.context; }
    if (((token === import21.RequiredValidator) && (28 === requestNodeIndex))) { return this._RequiredValidator_28_4.context; }
    if (((token === import22.NG_VALIDATORS) && (28 === requestNodeIndex))) { return this._NG_VALIDATORS_28_5; }
    if (((token === import23.NG_VALUE_ACCESSOR) && (28 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_28_6; }
    if (((token === import24.NgModel) && (28 === requestNodeIndex))) { return this._NgModel_28_7.context; }
    if (((token === import25.NgControl) && (28 === requestNodeIndex))) { return this._NgControl_28_8; }
    if (((token === import26.NgControlStatus) && (28 === requestNodeIndex))) { return this._NgControlStatus_28_9.context; }
    if (((token === import20.DefaultValueAccessor) && (36 === requestNodeIndex))) { return this._DefaultValueAccessor_36_3.context; }
    if (((token === import21.RequiredValidator) && (36 === requestNodeIndex))) { return this._RequiredValidator_36_4.context; }
    if (((token === import22.NG_VALIDATORS) && (36 === requestNodeIndex))) { return this._NG_VALIDATORS_36_5; }
    if (((token === import23.NG_VALUE_ACCESSOR) && (36 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_36_6; }
    if (((token === import24.NgModel) && (36 === requestNodeIndex))) { return this._NgModel_36_7.context; }
    if (((token === import25.NgControl) && (36 === requestNodeIndex))) { return this._NgControl_36_8; }
    if (((token === import26.NgControlStatus) && (36 === requestNodeIndex))) { return this._NgControlStatus_36_9.context; }
    if (((token === import16.MdButton) && ((39 <= requestNodeIndex) && (requestNodeIndex <= 40)))) { return this._MdButton_39_3.context; }
    if (((token === import27.NgForm) && ((8 <= requestNodeIndex) && (requestNodeIndex <= 41)))) { return this._NgForm_8_3.context; }
    if (((token === import28.ControlContainer) && ((8 <= requestNodeIndex) && (requestNodeIndex <= 41)))) { return this._ControlContainer_8_4; }
    if (((token === import26.NgControlStatusGroup) && ((8 <= requestNodeIndex) && (requestNodeIndex <= 41)))) { return this._NgControlStatusGroup_8_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._NgForm_8_3.ngDoCheck(this,this._el_8,throwOnChange);
    this._NgControlStatusGroup_8_5.ngDoCheck(this,this._el_8,throwOnChange);
    this._DefaultValueAccessor_15_3.ngDoCheck(this,this._el_15,throwOnChange);
    const currVal_15_1_0:any = '';
    this._RequiredValidator_15_4.check_required(currVal_15_1_0,throwOnChange,false);
    this._RequiredValidator_15_4.ngDoCheck(this,this._el_15,throwOnChange);
    const currVal_15_2_0:any = 'regEmail';
    this._NgModel_15_7.check_name(currVal_15_2_0,throwOnChange,false);
    const currVal_15_2_1:any = this.parentView.context.model.regEmail;
    this._NgModel_15_7.check_model(currVal_15_2_1,throwOnChange,false);
    this._NgModel_15_7.ngDoCheck(this,this._el_15,throwOnChange);
    this._NgControlStatus_15_9.ngDoCheck(this,this._el_15,throwOnChange);
    const currVal_26_0_0:any = this.parentView.context.passwordRequirements;
    this._NgIf_26_6.check_ngIf(currVal_26_0_0,throwOnChange,false);
    this._NgIf_26_6.ngDoCheck(this,this._anchor_26,throwOnChange);
    this._DefaultValueAccessor_28_3.ngDoCheck(this,this._el_28,throwOnChange);
    const currVal_28_1_0:any = '';
    this._RequiredValidator_28_4.check_required(currVal_28_1_0,throwOnChange,false);
    this._RequiredValidator_28_4.ngDoCheck(this,this._el_28,throwOnChange);
    const currVal_28_2_0:any = 'regPassword';
    this._NgModel_28_7.check_name(currVal_28_2_0,throwOnChange,false);
    const currVal_28_2_1:any = this.parentView.context.model.regPassword;
    this._NgModel_28_7.check_model(currVal_28_2_1,throwOnChange,false);
    this._NgModel_28_7.ngDoCheck(this,this._el_28,throwOnChange);
    this._NgControlStatus_28_9.ngDoCheck(this,this._el_28,throwOnChange);
    this._DefaultValueAccessor_36_3.ngDoCheck(this,this._el_36,throwOnChange);
    const currVal_36_1_0:any = '';
    this._RequiredValidator_36_4.check_required(currVal_36_1_0,throwOnChange,false);
    this._RequiredValidator_36_4.ngDoCheck(this,this._el_36,throwOnChange);
    const currVal_36_2_0:any = 'regConfirmPassword';
    this._NgModel_36_7.check_name(currVal_36_2_0,throwOnChange,false);
    const currVal_36_2_1:any = this.parentView.context.model.regConfirmPassword;
    this._NgModel_36_7.check_model(currVal_36_2_1,throwOnChange,false);
    this._NgModel_36_7.ngDoCheck(this,this._el_36,throwOnChange);
    this._NgControlStatus_36_9.ngDoCheck(this,this._el_36,throwOnChange);
    const currVal_39_0_0:boolean = !this._NgForm_8_3.context.form.valid;
    this._MdButton_39_3.check_disabled(currVal_39_0_0,throwOnChange,false);
    if (this._MdButton_39_3.ngDoCheck(this,this._el_39,throwOnChange)) { this.compView_39.markAsCheckOnce(); }
    this._vc_26.detectChangesInNestedViews(throwOnChange);
    this._NgControlStatusGroup_8_5.checkHost(this,this,this._el_8,throwOnChange);
    this._RequiredValidator_15_4.checkHost(this,this,this._el_15,throwOnChange);
    this._NgControlStatus_15_9.checkHost(this,this,this._el_15,throwOnChange);
    const currVal_72:any = import3.inlineInterpolate(1,'',this.parentView.context.passwordReqText,'');
    if (import3.checkBinding(throwOnChange,this._expr_72,currVal_72)) {
      this.renderer.setElementProperty(this._el_23,'title',currVal_72);
      this._expr_72 = currVal_72;
    }
    this._RequiredValidator_28_4.checkHost(this,this,this._el_28,throwOnChange);
    this._NgControlStatus_28_9.checkHost(this,this,this._el_28,throwOnChange);
    this._RequiredValidator_36_4.checkHost(this,this,this._el_36,throwOnChange);
    this._NgControlStatus_36_9.checkHost(this,this,this._el_36,throwOnChange);
    this._MdButton_39_3.checkHost(this,this.compView_39,this._el_39,throwOnChange);
    this.compView_39.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this._vc_26.destroyNestedViews();
    this.compView_39.destroy();
    this._NgModel_15_7.ngOnDestroy();
    this._NgModel_28_7.ngOnDestroy();
    this._NgModel_36_7.ngOnDestroy();
    this._NgForm_8_3.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  visitProjectableNodesInternal(nodeIndex:number,ngContentIndex:number,cb:any,ctx:any):void {
    if (((nodeIndex == 39) && (ngContentIndex == 0))) { cb(this._text_40,ctx); }
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 26)) { return new View_LoginRegisterFormComponent3(this.viewUtils,this,26,this._anchor_26,this._vc_26); }
    return (null as any);
  }
  handleEvent_5(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.context.toggleLogin()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_8(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._NgForm_8_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngSubmit')) {
      const pd_sub_0:any = ((<any>this.parentView.context.registerUser($event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_15(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_15_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.parentView.context.model.regEmail = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_23(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.context.togglePassReq()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_28(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_28_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.parentView.context.model.regPassword = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_36(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_36_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.parentView.context.model.regConfirmPassword = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_39(eventName:string,$event:any):boolean {
    this.compView_39.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._MdButton_39_3.handleEvent(eventName,$event) && result);
    return result;
  }
}
var renderType_LoginRegisterFormComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,styles_LoginRegisterFormComponent,{});
export class View_LoginRegisterFormComponent0 extends import1.AppView<import0.LoginRegisterFormComponent> {
  _text_0:any;
  _anchor_1:any;
  /*private*/ _vc_1:import18.ViewContainer;
  _TemplateRef_1_5:any;
  _NgIf_1_6:import30.Wrapper_NgIf;
  _text_2:any;
  _text_3:any;
  _anchor_4:any;
  /*private*/ _vc_4:import18.ViewContainer;
  _TemplateRef_4_5:any;
  _NgIf_4_6:import30.Wrapper_NgIf;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_LoginRegisterFormComponent0,renderType_LoginRegisterFormComponent,import6.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._anchor_1 = this.renderer.createTemplateAnchor(parentRenderNode,(null as any));
    this._vc_1 = new import18.ViewContainer(1,(null as any),this,this._anchor_1);
    this._TemplateRef_1_5 = new import31.TemplateRef_(this,1,this._anchor_1);
    this._NgIf_1_6 = new import30.Wrapper_NgIf(this._vc_1.vcRef,this._TemplateRef_1_5);
    this._text_2 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._text_3 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._anchor_4 = this.renderer.createTemplateAnchor(parentRenderNode,(null as any));
    this._vc_4 = new import18.ViewContainer(4,(null as any),this,this._anchor_4);
    this._TemplateRef_4_5 = new import31.TemplateRef_(this,4,this._anchor_4);
    this._NgIf_4_6 = new import30.Wrapper_NgIf(this._vc_4.vcRef,this._TemplateRef_4_5);
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._text_0,
      this._anchor_1,
      this._text_2,
      this._text_3,
      this._anchor_4
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import31.TemplateRef) && (1 === requestNodeIndex))) { return this._TemplateRef_1_5; }
    if (((token === import32.NgIf) && (1 === requestNodeIndex))) { return this._NgIf_1_6.context; }
    if (((token === import31.TemplateRef) && (4 === requestNodeIndex))) { return this._TemplateRef_4_5; }
    if (((token === import32.NgIf) && (4 === requestNodeIndex))) { return this._NgIf_4_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_1_0_0:any = this.context.showLogin;
    this._NgIf_1_6.check_ngIf(currVal_1_0_0,throwOnChange,false);
    this._NgIf_1_6.ngDoCheck(this,this._anchor_1,throwOnChange);
    const currVal_4_0_0:any = this.context.showRegister;
    this._NgIf_4_6.check_ngIf(currVal_4_0_0,throwOnChange,false);
    this._NgIf_4_6.ngDoCheck(this,this._anchor_4,throwOnChange);
    this._vc_1.detectChangesInNestedViews(throwOnChange);
    this._vc_4.detectChangesInNestedViews(throwOnChange);
  }
  destroyInternal():void {
    this._vc_1.destroyNestedViews();
    this._vc_4.destroyNestedViews();
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 1)) { return new View_LoginRegisterFormComponent1(this.viewUtils,this,1,this._anchor_1,this._vc_1); }
    if ((nodeIndex == 4)) { return new View_LoginRegisterFormComponent2(this.viewUtils,this,4,this._anchor_4,this._vc_4); }
    return (null as any);
  }
}