/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../app/components/navigation.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '../../../app/services/authentication.service';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/constants';
import * as import8 from '@angular/core/src/linker/component_factory';
import * as import9 from '@angular/http/src/http';
import * as import10 from '@angular/router/src/router';
import * as import11 from '../../node_modules/@angular/router/src/directives/router_link.ngfactory';
import * as import12 from '@angular/core/src/change_detection/change_detection_util';
import * as import13 from '@angular/router/src/router_state';
import * as import14 from '@angular/common/src/location/location_strategy';
import * as import15 from '@angular/router/src/directives/router_link';
export class Wrapper_NavigationComponent {
  /*private*/ _eventHandler:Function;
  context:import0.NavigationComponent;
  /*private*/ _changed:boolean;
  constructor(p0:any,p1:any) {
    this._changed = false;
    this.context = new import0.NavigationComponent(p0,p1);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_NavigationComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_NavigationComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.NavigationComponent>;
  _AuthenticationService_0_3:import5.AuthenticationService;
  _NavigationComponent_0_4:Wrapper_NavigationComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_NavigationComponent_Host0,renderType_NavigationComponent_Host,import6.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'app-navigation',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_NavigationComponent0(this.viewUtils,this,0,this._el_0);
    this._AuthenticationService_0_3 = new import5.AuthenticationService(this.injectorGet(import9.Http,this.parentIndex));
    this._NavigationComponent_0_4 = new Wrapper_NavigationComponent(this._AuthenticationService_0_3,this.injectorGet(import10.Router,this.parentIndex));
    this.compView_0.create(this._NavigationComponent_0_4.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import8.ComponentRef_<any>(0,this,this._el_0,this._NavigationComponent_0_4.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import5.AuthenticationService) && (0 === requestNodeIndex))) { return this._AuthenticationService_0_3; }
    if (((token === import0.NavigationComponent) && (0 === requestNodeIndex))) { return this._NavigationComponent_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._NavigationComponent_0_4.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const NavigationComponentNgFactory:import8.ComponentFactory<import0.NavigationComponent> = new import8.ComponentFactory<import0.NavigationComponent>('app-navigation',View_NavigationComponent_Host0,import0.NavigationComponent);
const styles_NavigationComponent:any[] = ([] as any[]);
var renderType_NavigationComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,styles_NavigationComponent,{});
export class View_NavigationComponent0 extends import1.AppView<import0.NavigationComponent> {
  _text_0:any;
  _el_1:any;
  _text_2:any;
  _el_3:any;
  _el_4:any;
  _RouterLinkWithHref_4_3:import11.Wrapper_RouterLinkWithHref;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  _el_8:any;
  _RouterLinkWithHref_8_3:import11.Wrapper_RouterLinkWithHref;
  _text_9:any;
  _text_10:any;
  _el_11:any;
  _el_12:any;
  _RouterLinkWithHref_12_3:import11.Wrapper_RouterLinkWithHref;
  _text_13:any;
  _text_14:any;
  _el_15:any;
  _el_16:any;
  _text_17:any;
  _text_18:any;
  /*private*/ _expr_22:any;
  /*private*/ _expr_23:any;
  /*private*/ _expr_24:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_NavigationComponent0,renderType_NavigationComponent,import6.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways);
    this._expr_22 = import12.UNINITIALIZED;
    this._expr_23 = import12.UNINITIALIZED;
    this._expr_24 = import12.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._text_0 = this.renderer.createText(parentRenderNode,' ',(null as any));
    this._el_1 = import3.createRenderElement(this.renderer,parentRenderNode,'ul',new import3.InlineArray2(2,'class','nav nav-pills'),(null as any));
    this._text_2 = this.renderer.createText(this._el_1,'\n    ',(null as any));
    this._el_3 = import3.createRenderElement(this.renderer,this._el_1,'li',new import3.InlineArray2(2,'role','presentation'),(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_3,'a',new import3.InlineArray2(2,'routerLink','/dashboard'),(null as any));
    this._RouterLinkWithHref_4_3 = new import11.Wrapper_RouterLinkWithHref(this.parentView.injectorGet(import10.Router,this.parentIndex),this.parentView.injectorGet(import13.ActivatedRoute,this.parentIndex),this.parentView.injectorGet(import14.LocationStrategy,this.parentIndex));
    this._text_5 = this.renderer.createText(this._el_4,'Dashboard',(null as any));
    this._text_6 = this.renderer.createText(this._el_1,'\n    ',(null as any));
    this._el_7 = import3.createRenderElement(this.renderer,this._el_1,'li',new import3.InlineArray2(2,'role','presentation'),(null as any));
    this._el_8 = import3.createRenderElement(this.renderer,this._el_7,'a',new import3.InlineArray2(2,'routerLink','/quizes'),(null as any));
    this._RouterLinkWithHref_8_3 = new import11.Wrapper_RouterLinkWithHref(this.parentView.injectorGet(import10.Router,this.parentIndex),this.parentView.injectorGet(import13.ActivatedRoute,this.parentIndex),this.parentView.injectorGet(import14.LocationStrategy,this.parentIndex));
    this._text_9 = this.renderer.createText(this._el_8,'My Quizes',(null as any));
    this._text_10 = this.renderer.createText(this._el_1,'\n    ',(null as any));
    this._el_11 = import3.createRenderElement(this.renderer,this._el_1,'li',new import3.InlineArray2(2,'role','presentation'),(null as any));
    this._el_12 = import3.createRenderElement(this.renderer,this._el_11,'a',new import3.InlineArray2(2,'routerLink','/results'),(null as any));
    this._RouterLinkWithHref_12_3 = new import11.Wrapper_RouterLinkWithHref(this.parentView.injectorGet(import10.Router,this.parentIndex),this.parentView.injectorGet(import13.ActivatedRoute,this.parentIndex),this.parentView.injectorGet(import14.LocationStrategy,this.parentIndex));
    this._text_13 = this.renderer.createText(this._el_12,'My Results',(null as any));
    this._text_14 = this.renderer.createText(this._el_1,'\n    ',(null as any));
    this._el_15 = import3.createRenderElement(this.renderer,this._el_1,'li',new import3.InlineArray2(2,'role','presentation'),(null as any));
    this._el_16 = import3.createRenderElement(this.renderer,this._el_15,'a',new import3.InlineArray2(2,'href','#'),(null as any));
    this._text_17 = this.renderer.createText(this._el_16,'Logout',(null as any));
    this._text_18 = this.renderer.createText(this._el_1,'\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_4,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_4));
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_8,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_8));
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_12,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_12));
    var disposable_3:Function = import3.subscribeToRenderElement(this,this._el_16,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_16));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._el_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._el_15,
      this._el_16,
      this._text_17,
      this._text_18
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import15.RouterLinkWithHref) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._RouterLinkWithHref_4_3.context; }
    if (((token === import15.RouterLinkWithHref) && ((8 <= requestNodeIndex) && (requestNodeIndex <= 9)))) { return this._RouterLinkWithHref_8_3.context; }
    if (((token === import15.RouterLinkWithHref) && ((12 <= requestNodeIndex) && (requestNodeIndex <= 13)))) { return this._RouterLinkWithHref_12_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_4_0_0:any = '/dashboard';
    this._RouterLinkWithHref_4_3.check_routerLink(currVal_4_0_0,throwOnChange,false);
    this._RouterLinkWithHref_4_3.ngDoCheck(this,this._el_4,throwOnChange);
    const currVal_8_0_0:any = '/quizes';
    this._RouterLinkWithHref_8_3.check_routerLink(currVal_8_0_0,throwOnChange,false);
    this._RouterLinkWithHref_8_3.ngDoCheck(this,this._el_8,throwOnChange);
    const currVal_12_0_0:any = '/results';
    this._RouterLinkWithHref_12_3.check_routerLink(currVal_12_0_0,throwOnChange,false);
    this._RouterLinkWithHref_12_3.ngDoCheck(this,this._el_12,throwOnChange);
    const currVal_22:any = this.context.dashboardActive;
    if (import3.checkBinding(throwOnChange,this._expr_22,currVal_22)) {
      this.renderer.setElementClass(this._el_3,'active',currVal_22);
      this._expr_22 = currVal_22;
    }
    this._RouterLinkWithHref_4_3.checkHost(this,this,this._el_4,throwOnChange);
    const currVal_23:any = this.context.myQuizesActive;
    if (import3.checkBinding(throwOnChange,this._expr_23,currVal_23)) {
      this.renderer.setElementClass(this._el_7,'active',currVal_23);
      this._expr_23 = currVal_23;
    }
    this._RouterLinkWithHref_8_3.checkHost(this,this,this._el_8,throwOnChange);
    const currVal_24:any = this.context.myResultsActive;
    if (import3.checkBinding(throwOnChange,this._expr_24,currVal_24)) {
      this.renderer.setElementClass(this._el_11,'active',currVal_24);
      this._expr_24 = currVal_24;
    }
    this._RouterLinkWithHref_12_3.checkHost(this,this,this._el_12,throwOnChange);
  }
  destroyInternal():void {
    this._RouterLinkWithHref_4_3.ngOnDestroy();
    this._RouterLinkWithHref_8_3.ngOnDestroy();
    this._RouterLinkWithHref_12_3.ngOnDestroy();
  }
  handleEvent_4(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLinkWithHref_4_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_8(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLinkWithHref_8_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_12(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLinkWithHref_12_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_16(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.logout($event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}